// Copyright 2026 patrik-zita. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Adresa struct {
	CisloDoAdresy           string `json:"cisloDoAdresy"`
	CisloDomovni            int    `json:"cisloDomovni"`
	CisloOrientacni         int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno  string `json:"cisloOrientacniPismeno"`
	DoplnekAdresy           string `json:"doplnekAdresy"`
	KodAdresnihoMista       int    `json:"kodAdresnihoMista"`
	KodCastiObce            int    `json:"kodCastiObce"`
	KodKraje                int    `json:"kodKraje"`
	KodMestskeCastiObvodu   int    `json:"kodMestskeCastiObvodu"`
	KodMestskehoObvodu      int    `json:"kodMestskehoObvodu"`
	KodObce                 int    `json:"kodObce"`
	KodOkresu               int    `json:"kodOkresu"`
	KodSpravnihoObvodu      int    `json:"kodSpravnihoObvodu"`
	KodStatu                string `json:"kodStatu"`
	KodUlice                int    `json:"kodUlice"`
	NazevCastiObce          string `json:"nazevCastiObce"`
	NazevKraje              string `json:"nazevKraje"`
	NazevMestskeCastiObvodu string `json:"nazevMestskeCastiObvodu"`
	NazevMestskehoObvodu    string `json:"nazevMestskehoObvodu"`
	NazevObce               string `json:"nazevObce"`
	NazevOkresu             string `json:"nazevOkresu"`
	NazevSpravnihoObvodu    string `json:"nazevSpravnihoObvodu"`
	NazevStatu              string `json:"nazevStatu"`
	NazevUlice              string `json:"nazevUlice"`
	Psc                     int    `json:"psc"`
	PscTxt                  string `json:"pscTxt"`
	StandardizaceAdresy     bool   `json:"standardizaceAdresy"`
	TextovaAdresa           string `json:"textovaAdresa"`
	TypCisloDomovni         int    `json:"typCisloDomovni"`
}

type AdresaAres struct {
	PlatnostDo     string          `json:"platnostDo"`
	PlatnostOd     string          `json:"platnostOd"`
	PrimarniZaznam bool            `json:"primarniZaznam"`
	Sidlo          json.RawMessage `json:"sidlo"`
}

type AdresaCeu struct {
	CisloDoAdresy           string `json:"cisloDoAdresy"`
	CisloDomovni            int    `json:"cisloDomovni"`
	CisloOrientacni         int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno  string `json:"cisloOrientacniPismeno"`
	DoplnekAdresy           string `json:"doplnekAdresy"`
	KodAdresnihoMista       int    `json:"kodAdresnihoMista"`
	KodCastiObce            int    `json:"kodCastiObce"`
	KodKraje                int    `json:"kodKraje"`
	KodMestskeCastiObvodu   int    `json:"kodMestskeCastiObvodu"`
	KodMestskehoObvodu      int    `json:"kodMestskehoObvodu"`
	KodObce                 int    `json:"kodObce"`
	KodOkresu               int    `json:"kodOkresu"`
	KodSpravnihoObvodu      int    `json:"kodSpravnihoObvodu"`
	KodStatu                string `json:"kodStatu"`
	KodUlice                int    `json:"kodUlice"`
	NazevCastiObce          string `json:"nazevCastiObce"`
	NazevKraje              string `json:"nazevKraje"`
	NazevMestskeCastiObvodu string `json:"nazevMestskeCastiObvodu"`
	NazevMestskehoObvodu    string `json:"nazevMestskehoObvodu"`
	NazevObce               string `json:"nazevObce"`
	NazevOkresu             string `json:"nazevOkresu"`
	NazevSpravnihoObvodu    string `json:"nazevSpravnihoObvodu"`
	NazevStatu              string `json:"nazevStatu"`
	NazevUlice              string `json:"nazevUlice"`
	Psc                     int    `json:"psc"`
	PscTxt                  string `json:"pscTxt"`
	StandardizaceAdresy     bool   `json:"standardizaceAdresy"`
	TextovaAdresa           string `json:"textovaAdresa"`
	TypAdresy               string `json:"typAdresy"`
	TypCisloDomovni         int    `json:"typCisloDomovni"`
}

type AdresaDorucovaci struct {
	RadekAdresy1 string `json:"radekAdresy1"`
	RadekAdresy2 string `json:"radekAdresy2"`
	RadekAdresy3 string `json:"radekAdresy3"`
}

type AdresaFiltr struct {
	CisloDomovni           int    `json:"cisloDomovni"`
	CisloOrientacni        int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno string `json:"cisloOrientacniPismeno"`
	KodCastiObce           int    `json:"kodCastiObce"`
	KodMestskeCastiObvodu  int    `json:"kodMestskeCastiObvodu"`
	KodObce                int    `json:"kodObce"`
	KodSpravnihoObvodu     int    `json:"kodSpravnihoObvodu"`
	KodUlice               int    `json:"kodUlice"`
	TextovaAdresa          string `json:"textovaAdresa"`
}

type AdresaRcns struct {
	CisloDoAdresy           string `json:"cisloDoAdresy"`
	CisloDomovni            int    `json:"cisloDomovni"`
	CisloOrientacni         int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno  string `json:"cisloOrientacniPismeno"`
	DoplnekAdresy           string `json:"doplnekAdresy"`
	KodAdresnihoMista       int    `json:"kodAdresnihoMista"`
	KodCastiObce            int    `json:"kodCastiObce"`
	KodKraje                int    `json:"kodKraje"`
	KodMestskeCastiObvodu   int    `json:"kodMestskeCastiObvodu"`
	KodMestskehoObvodu      int    `json:"kodMestskehoObvodu"`
	KodObce                 int    `json:"kodObce"`
	KodOkresu               int    `json:"kodOkresu"`
	KodSpravnihoObvodu      int    `json:"kodSpravnihoObvodu"`
	KodStatu                string `json:"kodStatu"`
	KodUlice                int    `json:"kodUlice"`
	NazevCastiObce          string `json:"nazevCastiObce"`
	NazevKraje              string `json:"nazevKraje"`
	NazevMestskeCastiObvodu string `json:"nazevMestskeCastiObvodu"`
	NazevMestskehoObvodu    string `json:"nazevMestskehoObvodu"`
	NazevObce               string `json:"nazevObce"`
	NazevOkresu             string `json:"nazevOkresu"`
	NazevSpravnihoObvodu    string `json:"nazevSpravnihoObvodu"`
	NazevStatu              string `json:"nazevStatu"`
	NazevUlice              string `json:"nazevUlice"`
	PlatnostDo              string `json:"platnostDo"`
	PlatnostOd              string `json:"platnostOd"`
	Psc                     int    `json:"psc"`
	PscTxt                  string `json:"pscTxt"`
	StandardizaceAdresy     bool   `json:"standardizaceAdresy"`
	TextovaAdresa           string `json:"textovaAdresa"`
	TypAdresy               string `json:"typAdresy"`
	TypCisloDomovni         int    `json:"typCisloDomovni"`
}

type AdresaRos struct {
	CisloDoAdresy           string `json:"cisloDoAdresy"`
	CisloDomovni            int    `json:"cisloDomovni"`
	CisloOrientacni         int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno  string `json:"cisloOrientacniPismeno"`
	DoplnekAdresy           string `json:"doplnekAdresy"`
	KodAdresnihoMista       int    `json:"kodAdresnihoMista"`
	KodCastiObce            int    `json:"kodCastiObce"`
	KodKraje                int    `json:"kodKraje"`
	KodMestskeCastiObvodu   int    `json:"kodMestskeCastiObvodu"`
	KodMestskehoObvodu      int    `json:"kodMestskehoObvodu"`
	KodObce                 int    `json:"kodObce"`
	KodOkresu               int    `json:"kodOkresu"`
	KodSpravnihoObvodu      int    `json:"kodSpravnihoObvodu"`
	KodStatu                string `json:"kodStatu"`
	KodUlice                int    `json:"kodUlice"`
	NazevCastiObce          string `json:"nazevCastiObce"`
	NazevKraje              string `json:"nazevKraje"`
	NazevMestskeCastiObvodu string `json:"nazevMestskeCastiObvodu"`
	NazevMestskehoObvodu    string `json:"nazevMestskehoObvodu"`
	NazevObce               string `json:"nazevObce"`
	NazevOkresu             string `json:"nazevOkresu"`
	NazevSpravnihoObvodu    string `json:"nazevSpravnihoObvodu"`
	NazevStatu              string `json:"nazevStatu"`
	NazevUlice              string `json:"nazevUlice"`
	Psc                     int    `json:"psc"`
	PscTxt                  string `json:"pscTxt"`
	StandardizaceAdresy     bool   `json:"standardizaceAdresy"`
	TextovaAdresa           string `json:"textovaAdresa"`
	TypAdresy               string `json:"typAdresy"`
	TypCisloDomovni         int    `json:"typCisloDomovni"`
}

type AdresaStavRos struct {
	CisloDoAdresy           string `json:"cisloDoAdresy"`
	CisloDomovni            int    `json:"cisloDomovni"`
	CisloOrientacni         int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno  string `json:"cisloOrientacniPismeno"`
	DoplnekAdresy           string `json:"doplnekAdresy"`
	KodAdresnihoMista       int    `json:"kodAdresnihoMista"`
	KodCastiObce            int    `json:"kodCastiObce"`
	KodKraje                int    `json:"kodKraje"`
	KodMestskeCastiObvodu   int    `json:"kodMestskeCastiObvodu"`
	KodMestskehoObvodu      int    `json:"kodMestskehoObvodu"`
	KodObce                 int    `json:"kodObce"`
	KodOkresu               int    `json:"kodOkresu"`
	KodSpravnihoObvodu      int    `json:"kodSpravnihoObvodu"`
	KodStatu                string `json:"kodStatu"`
	KodUlice                int    `json:"kodUlice"`
	NazevCastiObce          string `json:"nazevCastiObce"`
	NazevKraje              string `json:"nazevKraje"`
	NazevMestskeCastiObvodu string `json:"nazevMestskeCastiObvodu"`
	NazevMestskehoObvodu    string `json:"nazevMestskehoObvodu"`
	NazevObce               string `json:"nazevObce"`
	NazevOkresu             string `json:"nazevOkresu"`
	NazevSpravnihoObvodu    string `json:"nazevSpravnihoObvodu"`
	NazevStatu              string `json:"nazevStatu"`
	NazevUlice              string `json:"nazevUlice"`
	PlatnostUdajeRos        string `json:"platnostUdajeRos"`
	Psc                     int    `json:"psc"`
	PscTxt                  string `json:"pscTxt"`
	StandardizaceAdresy     bool   `json:"standardizaceAdresy"`
	TextovaAdresa           string `json:"textovaAdresa"`
	TypAdresy               string `json:"typAdresy"`
	TypCisloDomovni         int    `json:"typCisloDomovni"`
}

type AdresaVr struct {
	Adresa      json.RawMessage `json:"adresa"`
	DatumVymazu string          `json:"datumVymazu"`
	DatumZapisu string          `json:"datumZapisu"`
	TypAdresy   string          `json:"typAdresy"`
}

type AkcionarVr struct {
	ClenoveOrganu json.RawMessage `json:"clenoveOrganu"`
	DatumVymazu   string          `json:"datumVymazu"`
	DatumZapisu   string          `json:"datumZapisu"`
	NazevOrganu   string          `json:"nazevOrganu"`
	PocetClenu    json.RawMessage `json:"pocetClenu"`
	TypAkcionare  string          `json:"typAkcionare"`
	TypOrganu     string          `json:"typOrganu"`
}

type AngazmaClenstviVr struct {
	Clenstvi    json.RawMessage `json:"clenstvi"`
	Funkce      json.RawMessage `json:"funkce"`
	TextZaOsobu string          `json:"textZaOsobu"`
	TextZruseni string          `json:"textZruseni"`
}

type AngazmaFyzickaOsobaVr struct {
	Clenstvi     json.RawMessage `json:"clenstvi"`
	DatumVymazu  string          `json:"datumVymazu"`
	DatumZapisu  string          `json:"datumZapisu"`
	FyzickaOsoba json.RawMessage `json:"fyzickaOsoba"`
	NazevAngazma string          `json:"nazevAngazma"`
	TypAngazma   string          `json:"typAngazma"`
}

type AngazmaOsobaVr struct {
	Clenstvi       json.RawMessage `json:"clenstvi"`
	DatumVymazu    string          `json:"datumVymazu"`
	DatumZapisu    string          `json:"datumZapisu"`
	FyzickaOsoba   json.RawMessage `json:"fyzickaOsoba"`
	NazevAngazma   string          `json:"nazevAngazma"`
	PravnickaOsoba json.RawMessage `json:"pravnickaOsoba"`
	SkrytyUdaj     json.RawMessage `json:"skrytyUdaj"`
	TypAngazma     string          `json:"typAngazma"`
}

type AngazmaRcns struct {
	OsobaFyzicka   json.RawMessage `json:"osobaFyzicka"`
	OsobaPravnicka json.RawMessage `json:"osobaPravnicka"`
}

type AngazmaRos struct {
	OsobaFyzicka     json.RawMessage `json:"osobaFyzicka"`
	OsobaPravnicka   json.RawMessage `json:"osobaPravnicka"`
	PlatnostUdajeRos string          `json:"platnostUdajeRos"`
}

type AngazovanaOsoba struct {
	DatumNarozeni   string `json:"datumNarozeni"`
	Jmeno           string `json:"jmeno"`
	Prijmeni        string `json:"prijmeni"`
	TitulPredJmenem string `json:"titulPredJmenem"`
	TitulZaJmenem   string `json:"titulZaJmenem"`
}

type AngazovanaOsobaCeu struct {
	JmenoPrijmeni string `json:"jmenoPrijmeni"`
	TypAngazma    string `json:"typAngazma"`
}

type AngazovanaOsobaFiltr struct {
	DatumNarozeni string `json:"datumNarozeni"`
	Jmeno         string `json:"jmeno"`
	Prijmeni      string `json:"prijmeni"`
	RodneCislo    string `json:"rodneCislo"`
}

type AngazovanaOsobaNrpzs struct {
	DatumNarozeni   string `json:"datumNarozeni"`
	Jmeno           string `json:"jmeno"`
	Prijmeni        string `json:"prijmeni"`
	TitulPredJmenem string `json:"titulPredJmenem"`
	TitulZaJmenem   string `json:"titulZaJmenem"`
	TypAngazma      string `json:"typAngazma"`
}

type AngazovanaOsobaRcns struct {
	DatumNarozeni   string `json:"datumNarozeni"`
	Jmeno           string `json:"jmeno"`
	KodStatu        string `json:"kodStatu"`
	NazevOrganu     string `json:"nazevOrganu"`
	PlatnostDo      string `json:"platnostDo"`
	PlatnostOd      string `json:"platnostOd"`
	Poznamka        string `json:"poznamka"`
	PravniForma     string `json:"pravniForma"`
	Prijmeni        string `json:"prijmeni"`
	TitulPredJmenem string `json:"titulPredJmenem"`
	TitulZaJmenem   string `json:"titulZaJmenem"`
	TypAngazma      string `json:"typAngazma"`
}

type AngazovanaOsobaRos struct {
	OsobaRob json.RawMessage `json:"osobaRob"`
	OsobaRos json.RawMessage `json:"osobaRos"`
}

type AngazovanaOsobaRpsh struct {
	Adresa          json.RawMessage `json:"adresa"`
	DatumNarozeni   string          `json:"datumNarozeni"`
	Funkce          string          `json:"funkce"`
	Jmeno           string          `json:"jmeno"`
	Kod             string          `json:"kod"`
	PlatnostDo      string          `json:"platnostDo"`
	PlatnostOd      string          `json:"platnostOd"`
	Prijmeni        string          `json:"prijmeni"`
	TitulPredJmenem string          `json:"titulPredJmenem"`
	TitulZaJmenem   string          `json:"titulZaJmenem"`
	TypAngazma      string          `json:"typAngazma"`
}

type AngazovanaOsobaRs struct {
	DatumNarozeni   string `json:"datumNarozeni"`
	Jmeno           string `json:"jmeno"`
	Prijmeni        string `json:"prijmeni"`
	TitulPredJmenem string `json:"titulPredJmenem"`
	TitulZaJmenem   string `json:"titulZaJmenem"`
	TypAngazma      string `json:"typAngazma"`
}

type AngazovanaOsobaRzp struct {
	DatumNarozeni   string `json:"datumNarozeni"`
	Jmeno           string `json:"jmeno"`
	PlatnostDo      string `json:"platnostDo"`
	PlatnostOd      string `json:"platnostOd"`
	Prijmeni        string `json:"prijmeni"`
	StatniObcanstvi string `json:"statniObcanstvi"`
	TitulPredJmenem string `json:"titulPredJmenem"`
	TitulZaJmenem   string `json:"titulZaJmenem"`
	TypAngazma      string `json:"typAngazma"`
}

type AngazovanaOsobaSzrZaklad struct {
	DatumNarozeni   string `json:"datumNarozeni"`
	Jmeno           string `json:"jmeno"`
	Prijmeni        string `json:"prijmeni"`
	TitulPredJmenem string `json:"titulPredJmenem"`
	TitulZaJmenem   string `json:"titulZaJmenem"`
	TypAngazma      string `json:"typAngazma"`
}

type AngazovanySubjektAdresa struct {
	CisloDoAdresy           string `json:"cisloDoAdresy"`
	CisloDomovni            int    `json:"cisloDomovni"`
	CisloOrientacni         int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno  string `json:"cisloOrientacniPismeno"`
	DoplnekAdresy           string `json:"doplnekAdresy"`
	KodAdresnihoMista       int    `json:"kodAdresnihoMista"`
	KodCastiObce            int    `json:"kodCastiObce"`
	KodKraje                int    `json:"kodKraje"`
	KodMestskeCastiObvodu   int    `json:"kodMestskeCastiObvodu"`
	KodMestskehoObvodu      int    `json:"kodMestskehoObvodu"`
	KodObce                 int    `json:"kodObce"`
	KodOkresu               int    `json:"kodOkresu"`
	KodSpravnihoObvodu      int    `json:"kodSpravnihoObvodu"`
	KodStatu                string `json:"kodStatu"`
	KodUlice                int    `json:"kodUlice"`
	NazevCastiObce          string `json:"nazevCastiObce"`
	NazevKraje              string `json:"nazevKraje"`
	NazevMestskeCastiObvodu string `json:"nazevMestskeCastiObvodu"`
	NazevMestskehoObvodu    string `json:"nazevMestskehoObvodu"`
	NazevObce               string `json:"nazevObce"`
	NazevOkresu             string `json:"nazevOkresu"`
	NazevSpravnihoObvodu    string `json:"nazevSpravnihoObvodu"`
	NazevStatu              string `json:"nazevStatu"`
	NazevUlice              string `json:"nazevUlice"`
	PlatnostDo              string `json:"platnostDo"`
	PlatnostOd              string `json:"platnostOd"`
	Psc                     int    `json:"psc"`
	PscTxt                  string `json:"pscTxt"`
	StandardizaceAdresy     bool   `json:"standardizaceAdresy"`
	TextovaAdresa           string `json:"textovaAdresa"`
	TypCisloDomovni         int    `json:"typCisloDomovni"`
}

type AngazovanySubjektRcns struct {
	Dic              string          `json:"dic"`
	Ico              string          `json:"ico"`
	KodStatu         string          `json:"kodStatu"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	PlatnostDo       string          `json:"platnostDo"`
	PlatnostOd       string          `json:"platnostOd"`
	PravniForma      string          `json:"pravniForma"`
	Sidlo            json.RawMessage `json:"sidlo"`
	StatutarniOrgany json.RawMessage `json:"statutarniOrgany"`
}

type AngazovanySubjektRcnsZaklad struct {
	Dic           string          `json:"dic"`
	Ico           string          `json:"ico"`
	KodStatu      string          `json:"kodStatu"`
	ObchodniJmeno string          `json:"obchodniJmeno"`
	PlatnostDo    string          `json:"platnostDo"`
	PlatnostOd    string          `json:"platnostOd"`
	PravniForma   string          `json:"pravniForma"`
	Sidlo         json.RawMessage `json:"sidlo"`
}

type AngazovanySubjektRos struct {
	Adresy        json.RawMessage `json:"adresy"`
	Ico           string          `json:"ico"`
	ObchodniJmeno string          `json:"obchodniJmeno"`
}

type AngazovanySubjektRs struct {
	Adresa                json.RawMessage `json:"adresa"`
	DatumVzniku           string          `json:"datumVzniku"`
	DatumZaniku           string          `json:"datumZaniku"`
	Ico                   string          `json:"ico"`
	ObchodniJmeno         string          `json:"obchodniJmeno"`
	ObchodniJmenoZkracene string          `json:"obchodniJmenoZkracene"`
	PravniForma           string          `json:"pravniForma"`
	TypAngazma            string          `json:"typAngazma"`
}

type AngazovanySubjektRzp struct {
	Ico           string          `json:"ico"`
	KodStatu      string          `json:"kodStatu"`
	ObchodniJmeno string          `json:"obchodniJmeno"`
	OsobyZastupce json.RawMessage `json:"osobyZastupce"`
	PlatnostDo    string          `json:"platnostDo"`
	PlatnostOd    string          `json:"platnostOd"`
	PravniForma   string          `json:"pravniForma"`
	Sidlo         json.RawMessage `json:"sidlo"`
	TypAngazma    string          `json:"typAngazma"`
	TypSubjektu   string          `json:"typSubjektu"`
}

type AngazovanySubjektRzpZaklad struct {
	Ico           string          `json:"ico"`
	KodStatu      string          `json:"kodStatu"`
	ObchodniJmeno string          `json:"obchodniJmeno"`
	PlatnostDo    string          `json:"platnostDo"`
	PlatnostOd    string          `json:"platnostOd"`
	PravniForma   string          `json:"pravniForma"`
	Sidlo         json.RawMessage `json:"sidlo"`
	TypAngazma    string          `json:"typAngazma"`
	TypSubjektu   string          `json:"typSubjektu"`
}

type Chyba struct {
	Kod    string `json:"kod"`
	Popis  string `json:"popis"`
	SubKod string `json:"subKod"`
}

type Chyby struct {
	Chyby json.RawMessage `json:"chyby"`
}

type CinnostiVr struct {
	DoplnkovaCinnost json.RawMessage `json:"doplnkovaCinnost"`
	PredmetCinnosti  json.RawMessage `json:"predmetCinnosti"`
	PredmetPodnikani json.RawMessage `json:"predmetPodnikani"`
	Ucel             json.RawMessage `json:"ucel"`
}

type Ciselnik struct {
	KodCiselniku     string          `json:"kodCiselniku"`
	NazevCiselniku   string          `json:"nazevCiselniku"`
	PolozkyCiselniku json.RawMessage `json:"polozkyCiselniku"`
	ZdrojCiselniku   string          `json:"zdrojCiselniku"`
}

type CiselnikyNazevnikSeznam struct {
	Ciselniky   json.RawMessage `json:"ciselniky"`
	PocetCelkem int             `json:"pocetCelkem"`
}

type CiselnikyZakladniFiltr struct {
	KodCiselniku   string          `json:"kodCiselniku"`
	Pocet          int             `json:"pocet"`
	Razeni         json.RawMessage `json:"razeni"`
	Start          int             `json:"start"`
	ZdrojCiselniku string          `json:"zdrojCiselniku"`
}

type ClenSvazu struct {
	Ico        string `json:"ico"`
	PlatnostDo string `json:"platnostDo"`
	PlatnostOd string `json:"platnostOd"`
}

type ClenstviVr struct {
	VznikClenstvi string `json:"vznikClenstvi"`
	ZanikClenstvi string `json:"zanikClenstvi"`
}

type DatovaSchrankaStavRos struct {
	IdentifikatorDs   string `json:"identifikatorDs"`
	PlatnostUdajeRos  string `json:"platnostUdajeRos"`
	TypDatoveSchranky string `json:"typDatoveSchranky"`
}

type DatumStavRob struct {
	Datum            string `json:"datum"`
	PlatnostUdajeRob string `json:"platnostUdajeRob"`
	ZmenaUdaje       string `json:"zmenaUdaje"`
}

type DatumStavRos struct {
	Datum            string `json:"datum"`
	PlatnostUdajeRos string `json:"platnostUdajeRos"`
}

type DatumVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Hodnota     string `json:"hodnota"`
}

type DatumZapisuVymazuUdajeVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
}

type EkonomickeSubjektyCeuSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyKomplexFiltr struct {
	CzNace         json.RawMessage `json:"czNace"`
	FinancniUrad   json.RawMessage `json:"financniUrad"`
	Ico            json.RawMessage `json:"ico"`
	ObchodniJmeno  string          `json:"obchodniJmeno"`
	Pocet          int             `json:"pocet"`
	PravniForma    json.RawMessage `json:"pravniForma"`
	PravniFormaRos json.RawMessage `json:"pravniFormaRos"`
	Razeni         json.RawMessage `json:"razeni"`
	Sidlo          json.RawMessage `json:"sidlo"`
	Start          int             `json:"start"`
}

type EkonomickeSubjektyNotifikaceFiltr struct {
	DatovyZdroj string `json:"datovyZdroj"`
}

type EkonomickeSubjektyNrpzsSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyRcnsSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyRegistraceFiltr struct {
	Ico    json.RawMessage `json:"ico"`
	Pocet  int             `json:"pocet"`
	Razeni json.RawMessage `json:"razeni"`
	Start  int             `json:"start"`
}

type EkonomickeSubjektyResSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyRosSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyRpshSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyRsSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyRzpSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektySeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektySzrSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyVrSeznam struct {
	EkonomickeSubjekty json.RawMessage `json:"ekonomickeSubjekty"`
	PocetCelkem        int             `json:"pocetCelkem"`
}

type EkonomickeSubjektyZakladFiltr struct {
	FinancniUrad  json.RawMessage `json:"financniUrad"`
	Ico           json.RawMessage `json:"ico"`
	ObchodniJmeno string          `json:"obchodniJmeno"`
	Pocet         int             `json:"pocet"`
	PravniForma   json.RawMessage `json:"pravniForma"`
	Razeni        json.RawMessage `json:"razeni"`
	Sidlo         json.RawMessage `json:"sidlo"`
	Start         int             `json:"start"`
}

type EkonomickySubjekt struct {
	AdresaDorucovaci json.RawMessage `json:"adresaDorucovaci"`
	CzNace           json.RawMessage `json:"czNace"`
	CzNace2008       json.RawMessage `json:"czNace2008"`
	DalsiUdaje       json.RawMessage `json:"dalsiUdaje"`
	DatumAktualizace string          `json:"datumAktualizace"`
	DatumVzniku      string          `json:"datumVzniku"`
	DatumZaniku      string          `json:"datumZaniku"`
	Dic              string          `json:"dic"`
	DicSkDph         string          `json:"dicSkDph"`
	FinancniUrad     string          `json:"financniUrad"`
	Ico              string          `json:"ico"`
	IcoId            string          `json:"icoId"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	PravniForma      string          `json:"pravniForma"`
	PravniFormaRos   string          `json:"pravniFormaRos"`
	PrimarniZdroj    string          `json:"primarniZdroj"`
	SeznamRegistraci json.RawMessage `json:"seznamRegistraci"`
	Sidlo            json.RawMessage `json:"sidlo"`
	SubRegistrSzr    string          `json:"subRegistrSzr"`
}

type EkonomickySubjektCeu struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektCeuZaklad struct {
	Adresy           json.RawMessage `json:"adresy"`
	DatumAktualizace string          `json:"datumAktualizace"`
	DatumVzniku      string          `json:"datumVzniku"`
	DatumZaniku      string          `json:"datumZaniku"`
	Dic              string          `json:"dic"`
	FinancniUrad     string          `json:"financniUrad"`
	Ico              string          `json:"ico"`
	JmenoPrijmeni    string          `json:"jmenoPrijmeni"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	PravniForma      string          `json:"pravniForma"`
	PravniFormaRos   string          `json:"pravniFormaRos"`
	Sidlo            json.RawMessage `json:"sidlo"`
	TypSubjektu      string          `json:"typSubjektu"`
}

type EkonomickySubjektDalsiUdaje struct {
	DatovyZdroj    string          `json:"datovyZdroj"`
	ObchodniJmeno  json.RawMessage `json:"obchodniJmeno"`
	PravniForma    string          `json:"pravniForma"`
	PravniFormaRos string          `json:"pravniFormaRos"`
	Sidlo          json.RawMessage `json:"sidlo"`
	SpisovaZnacka  string          `json:"spisovaZnacka"`
}

type EkonomickySubjektEzpZaklad struct {
	DatumAktualizace string          `json:"datumAktualizace"`
	DatumVzniku      string          `json:"datumVzniku"`
	DatumZaniku      string          `json:"datumZaniku"`
	Dic              string          `json:"dic"`
	FinancniUrad     string          `json:"financniUrad"`
	Ico              string          `json:"ico"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	Odkaz            string          `json:"odkaz"`
	PravniForma      string          `json:"pravniForma"`
	PravniFormaRos   string          `json:"pravniFormaRos"`
	Sidlo            json.RawMessage `json:"sidlo"`
}

type EkonomickySubjektNrpzs struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektRcns struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektRes struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektRos struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektRpsh struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektRs struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektRzp struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektRzpAdresa struct {
	CisloDoAdresy           string `json:"cisloDoAdresy"`
	CisloDomovni            int    `json:"cisloDomovni"`
	CisloOrientacni         int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno  string `json:"cisloOrientacniPismeno"`
	DoplnekAdresy           string `json:"doplnekAdresy"`
	KodAdresnihoMista       int    `json:"kodAdresnihoMista"`
	KodCastiObce            int    `json:"kodCastiObce"`
	KodKraje                int    `json:"kodKraje"`
	KodMestskeCastiObvodu   int    `json:"kodMestskeCastiObvodu"`
	KodMestskehoObvodu      int    `json:"kodMestskehoObvodu"`
	KodObce                 int    `json:"kodObce"`
	KodOkresu               int    `json:"kodOkresu"`
	KodSpravnihoObvodu      int    `json:"kodSpravnihoObvodu"`
	KodStatu                string `json:"kodStatu"`
	KodUlice                int    `json:"kodUlice"`
	NazevCastiObce          string `json:"nazevCastiObce"`
	NazevKraje              string `json:"nazevKraje"`
	NazevMestskeCastiObvodu string `json:"nazevMestskeCastiObvodu"`
	NazevMestskehoObvodu    string `json:"nazevMestskehoObvodu"`
	NazevObce               string `json:"nazevObce"`
	NazevOkresu             string `json:"nazevOkresu"`
	NazevSpravnihoObvodu    string `json:"nazevSpravnihoObvodu"`
	NazevStatu              string `json:"nazevStatu"`
	NazevUlice              string `json:"nazevUlice"`
	PlatnostDo              string `json:"platnostDo"`
	PlatnostOd              string `json:"platnostOd"`
	Psc                     int    `json:"psc"`
	PscTxt                  string `json:"pscTxt"`
	StandardizaceAdresy     bool   `json:"standardizaceAdresy"`
	TextovaAdresa           string `json:"textovaAdresa"`
	TypAdresy               string `json:"typAdresy"`
	TypCisloDomovni         int    `json:"typCisloDomovni"`
}

type EkonomickySubjektSzr struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektVr struct {
	IcoId   string          `json:"icoId"`
	Zaznamy json.RawMessage `json:"zaznamy"`
}

type EkonomickySubjektZaklad struct {
	DatumAktualizace string          `json:"datumAktualizace"`
	DatumVzniku      string          `json:"datumVzniku"`
	DatumZaniku      string          `json:"datumZaniku"`
	Dic              string          `json:"dic"`
	FinancniUrad     string          `json:"financniUrad"`
	Ico              string          `json:"ico"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	PravniForma      string          `json:"pravniForma"`
	PravniFormaRos   string          `json:"pravniFormaRos"`
	Sidlo            json.RawMessage `json:"sidlo"`
}

type EmiseAkcieVr struct {
	DatumVymazu string          `json:"datumVymazu"`
	DatumZapisu string          `json:"datumZapisu"`
	Hodnota     json.RawMessage `json:"hodnota"`
	Pocet       int             `json:"pocet"`
	PodobaAkcie string          `json:"podobaAkcie"`
	Text        string          `json:"text"`
	TypAkcie    string          `json:"typAkcie"`
}

type EvidenceAgendaRos struct {
	AdresySidla          json.RawMessage `json:"adresySidla"`
	Agenda               string          `json:"agenda"`
	DatumVznikuOpravneni json.RawMessage `json:"datumVznikuOpravneni"`
	DatumZanikuOpravneni json.RawMessage `json:"datumZanikuOpravneni"`
	ObchodniJmeno        json.RawMessage `json:"obchodniJmeno"`
	Ovm                  string          `json:"ovm"`
	PozastaveniPreruseni json.RawMessage `json:"pozastaveniPreruseni"`
}

type Ezp struct {
	OsobaEzp   json.RawMessage `json:"osobaEzp"`
	SubjektEzp json.RawMessage `json:"subjektEzp"`
}

type FunkceVr struct {
	Nazev       string `json:"nazev"`
	VznikFunkce string `json:"vznikFunkce"`
	ZanikFunkce string `json:"zanikFunkce"`
}

type FyzickaOsobaVr struct {
	Adresa          json.RawMessage `json:"adresa"`
	Bydliste        json.RawMessage `json:"bydliste"`
	DatumNarozeni   string          `json:"datumNarozeni"`
	Jmeno           string          `json:"jmeno"`
	Prijmeni        string          `json:"prijmeni"`
	StatniObcanstvi string          `json:"statniObcanstvi"`
	TextOsoba       string          `json:"textOsoba"`
	TextOsobaDo     string          `json:"textOsobaDo"`
	TextOsobaOd     string          `json:"textOsobaOd"`
	TitulPredJmenem string          `json:"titulPredJmenem"`
	TitulZaJmenem   string          `json:"titulZaJmenem"`
}

type IcoVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Hodnota     string `json:"hodnota"`
}

type InsolvencniRizeni struct {
	DatumZapisu string `json:"datumZapisu"`
	PlatnostOd  string `json:"platnostOd"`
}

type InsolvencniRizeniVr struct {
	DatumVymazu      string          `json:"datumVymazu"`
	DatumZapisu      string          `json:"datumZapisu"`
	InsolvencniZapis json.RawMessage `json:"insolvencniZapis"`
	Spravce          json.RawMessage `json:"spravce"`
}

type InsolvencniZapisVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Text        string `json:"text"`
	TypZapisu   string `json:"typZapisu"`
}

type JmenoStavRob struct {
	Hodnota          string `json:"hodnota"`
	PlatnostUdajeRob string `json:"platnostUdajeRob"`
	ZmenaUdaje       string `json:"zmenaUdaje"`
}

type KategorieZoVr struct {
	DatumVymazu    string `json:"datumVymazu"`
	DatumZapisu    string `json:"datumZapisu"`
	TypKategorieZo string `json:"typKategorieZo"`
}

type KonkursVr struct {
	DatumRozhodnutiOs string          `json:"datumRozhodnutiOs"`
	DatumVymazu       string          `json:"datumVymazu"`
	DatumVyveseni     string          `json:"datumVyveseni"`
	DatumZapisu       string          `json:"datumZapisu"`
	SpisZnOs          string          `json:"spisZnOs"`
	Spravce           json.RawMessage `json:"spravce"`
	Text              string          `json:"text"`
	TypKonkursu       string          `json:"typKonkursu"`
	ZruseniKonkursu   json.RawMessage `json:"zruseniKonkursu"`
}

type KontaktniUdajeStavRos struct {
	Email            string `json:"email"`
	PlatnostUdajeRos string `json:"platnostUdajeRos"`
	Telefon          string `json:"telefon"`
}

type Kontakty struct {
	Email   string `json:"email"`
	Fax     string `json:"fax"`
	Telefon string `json:"telefon"`
	Www     string `json:"www"`
}

type KontaktyRs struct {
	Email   json.RawMessage `json:"email"`
	Fax     string          `json:"fax"`
	Telefon string          `json:"telefon"`
	Www     string          `json:"www"`
}

type NazevPolozky struct {
	KodJazyka string `json:"kodJazyka"`
	Nazev     string `json:"nazev"`
}

type Notifikace struct {
	IcoId    string `json:"icoId"`
	TypZmeny string `json:"typZmeny"`
}

type NotifikacniDavka struct {
	CisloDavky         int    `json:"cisloDavky"`
	DatovyZdroj        string `json:"datovyZdroj"`
	DatumUvolneniDavky string `json:"datumUvolneniDavky"`
	PocetZmen          int    `json:"pocetZmen"`
}

type NotifikacniDavkaZaznam struct {
	CisloDavky         int             `json:"cisloDavky"`
	DatovyZdroj        string          `json:"datovyZdroj"`
	DatumUvolneniDavky string          `json:"datumUvolneniDavky"`
	PocetZmen          int             `json:"pocetZmen"`
	SeznamNotifikaci   json.RawMessage `json:"seznamNotifikaci"`
}

type ObchodniJmenoAres struct {
	ObchodniJmeno  string `json:"obchodniJmeno"`
	PlatnostDo     string `json:"platnostDo"`
	PlatnostOd     string `json:"platnostOd"`
	PrimarniZaznam bool   `json:"primarniZaznam"`
}

type ObchodniJmenoCiziVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Hodnota     string `json:"hodnota"`
	Jazyk       string `json:"jazyk"`
}

type ObchodniJmenoStavRos struct {
	Hodnota          string `json:"hodnota"`
	PlatnostUdajeRos string `json:"platnostUdajeRos"`
}

type ObchodniJmenoVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Hodnota     string `json:"hodnota"`
}

type ObecnyTextVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Hodnota     string `json:"hodnota"`
}

type ObnosVr struct {
	Hodnota  string `json:"hodnota"`
	TypObnos string `json:"typObnos"`
}

type OdstepnyZavodVr struct {
	Cinnosti           json.RawMessage `json:"cinnosti"`
	DatumVymazu        string          `json:"datumVymazu"`
	DatumZapisu        string          `json:"datumZapisu"`
	Ico                json.RawMessage `json:"ico"`
	ObchodniJmeno      json.RawMessage `json:"obchodniJmeno"`
	OstatniSkutecnosti json.RawMessage `json:"ostatniSkutecnosti"`
	PravniForma        json.RawMessage `json:"pravniForma"`
	Sidlo              json.RawMessage `json:"sidlo"`
	Vedouci            json.RawMessage `json:"vedouci"`
}

type OrganVr struct {
	ClenoveOrganu json.RawMessage `json:"clenoveOrganu"`
	DatumVymazu   string          `json:"datumVymazu"`
	DatumZapisu   string          `json:"datumZapisu"`
	NazevOrganu   string          `json:"nazevOrganu"`
	PocetClenu    json.RawMessage `json:"pocetClenu"`
	TypOrganu     string          `json:"typOrganu"`
}

type OsobaRobZaklad struct {
	DatumNarozeni json.RawMessage `json:"datumNarozeni"`
	Jmeno         json.RawMessage `json:"jmeno"`
	Prijmeni      json.RawMessage `json:"prijmeni"`
}

type OsobaRos struct {
	DatumNarozeni string `json:"datumNarozeni"`
	OsobaTextem   string `json:"osobaTextem"`
}

type OsobaVr struct {
	Adresa      json.RawMessage `json:"adresa"`
	TextOsoba   string          `json:"textOsoba"`
	TextOsobaDo string          `json:"textOsobaDo"`
	TextOsobaOd string          `json:"textOsobaOd"`
}

type PocetClenuVr struct {
	DatumVymazu   string `json:"datumVymazu"`
	DatumZapisu   string `json:"datumZapisu"`
	MaxPocetClenu int    `json:"maxPocetClenu"`
	PocetClenu    int    `json:"pocetClenu"`
	Typ           string `json:"typ"`
}

type PodilVr struct {
	DatumVymazu    string          `json:"datumVymazu"`
	DatumZapisu    string          `json:"datumZapisu"`
	Splaceni       json.RawMessage `json:"splaceni"`
	Text           string          `json:"text"`
	VelikostPodilu json.RawMessage `json:"velikostPodilu"`
	Vklad          json.RawMessage `json:"vklad"`
	ZastavniPravo  json.RawMessage `json:"zastavniPravo"`
}

type PodnikatelVr struct {
	Bydliste        json.RawMessage `json:"bydliste"`
	DatumVymazu     string          `json:"datumVymazu"`
	DatumZapisu     string          `json:"datumZapisu"`
	NazevAngazma    string          `json:"nazevAngazma"`
	OsobaPodnikatel json.RawMessage `json:"osobaPodnikatel"`
	Pobyt           json.RawMessage `json:"pobyt"`
	TypAngazma      string          `json:"typAngazma"`
}

type PolozkaCiselniku struct {
	Kod          string          `json:"kod"`
	KodNadrizeny string          `json:"kodNadrizeny"`
	Nazev        json.RawMessage `json:"nazev"`
	PlatnostDo   string          `json:"platnostDo"`
	PlatnostOd   string          `json:"platnostOd"`
}

type PozastaveniPreruseniStavRos struct {
	Hodnota          bool   `json:"hodnota"`
	PlatnostUdajeRos string `json:"platnostUdajeRos"`
}

type PravniFormaStavRos struct {
	Hodnota          string `json:"hodnota"`
	PlatnostUdajeRos string `json:"platnostUdajeRos"`
}

type PravniFormaVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Hodnota     string `json:"hodnota"`
}

type PravniStavStavRos struct {
	Hodnota          string `json:"hodnota"`
	PlatnostUdajeRos string `json:"platnostUdajeRos"`
}

type PravnickaOsobaVr struct {
	Adresa        json.RawMessage `json:"adresa"`
	Ico           string          `json:"ico"`
	ObchodniJmeno string          `json:"obchodniJmeno"`
	PravniForma   string          `json:"pravniForma"`
	TextOsoba     string          `json:"textOsoba"`
	TextOsobaDo   string          `json:"textOsobaDo"`
	TextOsobaOd   string          `json:"textOsobaOd"`
	Zastoupeni    json.RawMessage `json:"zastoupeni"`
}

type PravoZvlastni struct {
	KodPravo   int    `json:"kodPravo"`
	PlatnostDo string `json:"platnostDo"`
	PlatnostOd string `json:"platnostOd"`
}

type PrijmeniStavRob struct {
	Hodnota          string `json:"hodnota"`
	PlatnostUdajeRob string `json:"platnostUdajeRob"`
	ZmenaUdaje       string `json:"zmenaUdaje"`
}

type Provozovna struct {
	Icp                   int             `json:"icp"`
	Nazev                 string          `json:"nazev"`
	OboryCinnosti         json.RawMessage `json:"oboryCinnosti"`
	PlatnostDo            string          `json:"platnostDo"`
	PlatnostOd            string          `json:"platnostOd"`
	PozastaveniProvozovny json.RawMessage `json:"pozastaveniProvozovny"`
	SidloProvozovny       json.RawMessage `json:"sidloProvozovny"`
	TypProvozovny         string          `json:"typProvozovny"`
	UmisteniProvozovny    string          `json:"umisteniProvozovny"`
}

type ProvozovnaRos struct {
	AdresaProvozovny      json.RawMessage `json:"adresaProvozovny"`
	DatumUkonceniCinnosti json.RawMessage `json:"datumUkonceniCinnosti"`
	DatumZahajeniCinnosti json.RawMessage `json:"datumZahajeniCinnosti"`
	Icp                   int             `json:"icp"`
}

type ProvozovnaZaklad struct {
	Icp                   int             `json:"icp"`
	Nazev                 string          `json:"nazev"`
	PlatnostDo            string          `json:"platnostDo"`
	PlatnostOd            string          `json:"platnostOd"`
	PozastaveniProvozovny json.RawMessage `json:"pozastaveniProvozovny"`
	SidloProvozovny       json.RawMessage `json:"sidloProvozovny"`
	TypProvozovny         string          `json:"typProvozovny"`
	UmisteniProvozovny    string          `json:"umisteniProvozovny"`
}

type ProvozovnyRzpStav struct {
	PocetAktivnich     int `json:"pocetAktivnich"`
	PocetCelkem        int `json:"pocetCelkem"`
	PocetPozastavenych int `json:"pocetPozastavenych"`
	PocetZaniklych     int `json:"pocetZaniklych"`
}

type RegistraceRcns struct {
	CisloRegistrace        string `json:"cisloRegistrace"`
	CisloZruseniRegistrace string `json:"cisloZruseniRegistrace"`
	DatumKonkurzu          string `json:"datumKonkurzu"`
	DatumLikvidace         string `json:"datumLikvidace"`
	DatumOpatrovnik        string `json:"datumOpatrovnik"`
	DatumZruseniRegistrace string `json:"datumZruseniRegistrace"`
}

type Seznam struct {
	PocetCelkem int `json:"pocetCelkem"`
}

type SeznamNotifikacnichDavek struct {
	NotifikacniDavky json.RawMessage `json:"notifikacniDavky"`
}

type SeznamRegistraci struct {
	StavZdrojeCeu     string `json:"stavZdrojeCeu"`
	StavZdrojeDph     string `json:"stavZdrojeDph"`
	StavZdrojeIr      string `json:"stavZdrojeIr"`
	StavZdrojeMonitor string `json:"stavZdrojeMonitor"`
	StavZdrojeNrpzs   string `json:"stavZdrojeNrpzs"`
	StavZdrojeRcns    string `json:"stavZdrojeRcns"`
	StavZdrojeRed     string `json:"stavZdrojeRed"`
	StavZdrojeRes     string `json:"stavZdrojeRes"`
	StavZdrojeRos     string `json:"stavZdrojeRos"`
	StavZdrojeRpsh    string `json:"stavZdrojeRpsh"`
	StavZdrojeRs      string `json:"stavZdrojeRs"`
	StavZdrojeRzp     string `json:"stavZdrojeRzp"`
	StavZdrojeSd      string `json:"stavZdrojeSd"`
	StavZdrojeSkDph   string `json:"stavZdrojeSkDph"`
	StavZdrojeSzr     string `json:"stavZdrojeSzr"`
	StavZdrojeVr      string `json:"stavZdrojeVr"`
}

type SkolaZarizeni struct {
	Adresa                json.RawMessage `json:"adresa"`
	DatumVzniku           string          `json:"datumVzniku"`
	DatumZaniku           string          `json:"datumZaniku"`
	Izo                   string          `json:"izo"`
	Kontakty              json.RawMessage `json:"kontakty"`
	ObchodniJmeno         string          `json:"obchodniJmeno"`
	ObchodniJmenoZkracene string          `json:"obchodniJmenoZkracene"`
	TypSkoly              string          `json:"typSkoly"`
}

type SpisovaZnackaVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Oddil       string `json:"oddil"`
	Soud        string `json:"soud"`
	Vlozka      int    `json:"vlozka"`
}

type SpolecniciVr struct {
	DatumVymazu   string          `json:"datumVymazu"`
	DatumZapisu   string          `json:"datumZapisu"`
	NazevOrganu   string          `json:"nazevOrganu"`
	Spolecnik     json.RawMessage `json:"spolecnik"`
	SpolecnyPodil json.RawMessage `json:"spolecnyPodil"`
	TypOrganu     string          `json:"typOrganu"`
	UvolnenyPodil json.RawMessage `json:"uvolnenyPodil"`
}

type SpolecnikVr struct {
	DatumVymazu string          `json:"datumVymazu"`
	DatumZapisu string          `json:"datumZapisu"`
	Osoba       json.RawMessage `json:"osoba"`
	Podil       json.RawMessage `json:"podil"`
}

type SpolecnyPodilVr struct {
	DatumVymazu string          `json:"datumVymazu"`
	DatumZapisu string          `json:"datumZapisu"`
	Podil       json.RawMessage `json:"podil"`
	Podilnik    json.RawMessage `json:"podilnik"`
}

type StandardizovanaAdresa struct {
	CisloDomovni            int    `json:"cisloDomovni"`
	CisloOrientacni         int    `json:"cisloOrientacni"`
	CisloOrientacniPismeno  string `json:"cisloOrientacniPismeno"`
	KodAdresnihoMista       int    `json:"kodAdresnihoMista"`
	KodCastiObce            int    `json:"kodCastiObce"`
	KodKraje                int    `json:"kodKraje"`
	KodMestskeCastiObvodu   int    `json:"kodMestskeCastiObvodu"`
	KodMestskehoObvoduP     int    `json:"kodMestskehoObvoduP"`
	KodObce                 int    `json:"kodObce"`
	KodOkresu               int    `json:"kodOkresu"`
	KodSpravnihoObvoduP     int    `json:"kodSpravnihoObvoduP"`
	KodStavebnihoObjektu    int    `json:"kodStavebnihoObjektu"`
	KodUlice                int    `json:"kodUlice"`
	NazevCastiObce          string `json:"nazevCastiObce"`
	NazevKraje              string `json:"nazevKraje"`
	NazevMestskeCastiObvodu string `json:"nazevMestskeCastiObvodu"`
	NazevMestskehoObvoduP   string `json:"nazevMestskehoObvoduP"`
	NazevObce               string `json:"nazevObce"`
	NazevOkresu             string `json:"nazevOkresu"`
	NazevSpravnihoObvoduP   string `json:"nazevSpravnihoObvoduP"`
	NazevUlice              string `json:"nazevUlice"`
	Psc                     int    `json:"psc"`
	TextovaAdresa           string `json:"textovaAdresa"`
	TypCisloDomovni         int    `json:"typCisloDomovni"`
	TypStavebnihoObjektu    string `json:"typStavebnihoObjektu"`
}

type StandardizovanaAdresaFiltr struct {
	CisloDomovni              int             `json:"cisloDomovni"`
	CisloOrientacni           int             `json:"cisloOrientacni"`
	CisloOrientacniPismeno    string          `json:"cisloOrientacniPismeno"`
	KodAdresnihoMista         int             `json:"kodAdresnihoMista"`
	KodCastiObce              int             `json:"kodCastiObce"`
	KodMestskehoCastiObvodu   int             `json:"kodMestskehoCastiObvodu"`
	KodObce                   int             `json:"kodObce"`
	KodUlice                  int             `json:"kodUlice"`
	NazevCastiObce            string          `json:"nazevCastiObce"`
	NazevMestskehoCastiObvodu string          `json:"nazevMestskehoCastiObvodu"`
	NazevObce                 string          `json:"nazevObce"`
	NazevUlice                string          `json:"nazevUlice"`
	Pocet                     int             `json:"pocet"`
	Razeni                    json.RawMessage `json:"razeni"`
	Start                     int             `json:"start"`
	TextovaAdresa             string          `json:"textovaAdresa"`
	TypStandardizaceAdresy    string          `json:"typStandardizaceAdresy"`
}

type StandardizovaneAdresySeznam struct {
	PocetCelkem           int             `json:"pocetCelkem"`
	Request               json.RawMessage `json:"request"`
	StandardizovaneAdresy json.RawMessage `json:"standardizovaneAdresy"`
	StavStandardizace     string          `json:"stavStandardizace"`
}

type StatistickeUdaje struct {
	InstitucionalniSektor2010 string `json:"institucionalniSektor2010"`
	KategoriePoctuPracovniku  string `json:"kategoriePoctuPracovniku"`
}

type StatutarniOrgan struct {
	PlatnostOd string `json:"platnostOd"`
	Popis      string `json:"popis"`
}

type StatutarniOrganRos struct {
	OsobaFyzicka     json.RawMessage `json:"osobaFyzicka"`
	OsobaPravnicka   json.RawMessage `json:"osobaPravnicka"`
	PlatnostUdajeRos string          `json:"platnostUdajeRos"`
}

type StatutarniOrganVr struct {
	ClenoveOrganu json.RawMessage `json:"clenoveOrganu"`
	DatumVymazu   string          `json:"datumVymazu"`
	DatumZapisu   string          `json:"datumZapisu"`
	NazevOrganu   string          `json:"nazevOrganu"`
	PocetClenu    json.RawMessage `json:"pocetClenu"`
	TypOrganu     string          `json:"typOrganu"`
	ZpusobJednani json.RawMessage `json:"zpusobJednani"`
}

type StatutarniOrganZastupciRos struct {
	Adresy           json.RawMessage `json:"adresy"`
	Ico              string          `json:"ico"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	PlatnostUdajeRos string          `json:"platnostUdajeRos"`
	Zastupci         json.RawMessage `json:"zastupci"`
}

type StatutatniOrganRcns struct {
	SubjektCirkev         json.RawMessage `json:"subjektCirkev"`
	SubjektPravnickaOsoba json.RawMessage `json:"subjektPravnickaOsoba"`
	SubjektSvazCirkvi     json.RawMessage `json:"subjektSvazCirkvi"`
}

type StavSubjektu struct {
	PlatnostOd   string `json:"platnostOd"`
	Popis        string `json:"popis"`
	StavSubjektu string `json:"stavSubjektu"`
}

type StavUdajeRob struct {
	PlatnostUdajeRob string `json:"platnostUdajeRob"`
	ZmenaUdaje       string `json:"zmenaUdaje"`
}

type StrankovaniARazeni struct {
	Pocet  int             `json:"pocet"`
	Razeni json.RawMessage `json:"razeni"`
	Start  int             `json:"start"`
}

type SubjektCirkev struct {
	CisloRegistracePrav        string          `json:"cisloRegistracePrav"`
	CisloZruseniRegistracePrav string          `json:"cisloZruseniRegistracePrav"`
	DatumRegistracePrav        string          `json:"datumRegistracePrav"`
	DatumZruseniRegistracePrav string          `json:"datumZruseniRegistracePrav"`
	IcoNastupce                string          `json:"icoNastupce"`
	Organy                     json.RawMessage `json:"organy"`
	PravoZvlastni              json.RawMessage `json:"pravoZvlastni"`
}

type SubjektCirkevZaklad struct {
	CisloRegistracePrav        string          `json:"cisloRegistracePrav"`
	CisloZruseniRegistracePrav string          `json:"cisloZruseniRegistracePrav"`
	DatumRegistracePrav        string          `json:"datumRegistracePrav"`
	DatumZruseniRegistracePrav string          `json:"datumZruseniRegistracePrav"`
	IcoNastupce                string          `json:"icoNastupce"`
	PravoZvlastni              json.RawMessage `json:"pravoZvlastni"`
}

type SubjektPravnickaOsoba struct {
	IcoNastupce             string          `json:"icoNastupce"`
	IcoZrizovatel           string          `json:"icoZrizovatel"`
	Organy                  json.RawMessage `json:"organy"`
	ZpusobZruseniRegistrace int             `json:"zpusobZruseniRegistrace"`
}

type SubjektPravnickaOsobaZaklad struct {
	IcoNastupce             string `json:"icoNastupce"`
	IcoZrizovatel           string `json:"icoZrizovatel"`
	ZpusobZruseniRegistrace int    `json:"zpusobZruseniRegistrace"`
}

type SubjektSvazCirkvi struct {
	ClenoveSvazu json.RawMessage `json:"clenoveSvazu"`
	IcoNastupce  string          `json:"icoNastupce"`
	Organy       json.RawMessage `json:"organy"`
}

type SubjektSvazCirkviZaklad struct {
	ClenoveSvazu json.RawMessage `json:"clenoveSvazu"`
	IcoNastupce  string          `json:"icoNastupce"`
}

type UpadekCeu struct {
	AkceUpadek string `json:"akceUpadek"`
	Datum      string `json:"datum"`
	Detail     string `json:"detail"`
	Podnet     string `json:"podnet"`
	SoudUpadek string `json:"soudUpadek"`
	SpisZn     string `json:"spisZn"`
	TypUpadek  string `json:"typUpadek"`
	Usneseni   string `json:"usneseni"`
}

type UpadekCeuVerejny struct {
	AkceUpadek    string          `json:"akceUpadek"`
	Datum         string          `json:"datum"`
	Detail        string          `json:"detail"`
	Podnet        string          `json:"podnet"`
	SoudUpadek    string          `json:"soudUpadek"`
	SpisZn        string          `json:"spisZn"`
	SpravceUpadku json.RawMessage `json:"spravceUpadku"`
	TypUpadek     string          `json:"typUpadek"`
	Usneseni      string          `json:"usneseni"`
}

type UvolnenyPodilVr struct {
	Clenstvi    json.RawMessage `json:"clenstvi"`
	DatumVymazu string          `json:"datumVymazu"`
	DatumZapisu string          `json:"datumZapisu"`
	Podil       json.RawMessage `json:"podil"`
}

type VkladVr struct {
	DatumVymazu string          `json:"datumVymazu"`
	DatumZapisu string          `json:"datumZapisu"`
	Text        string          `json:"text"`
	TypVkladu   string          `json:"typVkladu"`
	Vklad       json.RawMessage `json:"vklad"`
}

type ZakladniKapitalVr struct {
	DatumVymazu string          `json:"datumVymazu"`
	DatumZapisu string          `json:"datumZapisu"`
	Splaceni    json.RawMessage `json:"splaceni"`
	Text        string          `json:"text"`
	TypJmeni    string          `json:"typJmeni"`
	Vklad       json.RawMessage `json:"vklad"`
}

type ZastavniPravoVr struct {
	DatumVymazu          string `json:"datumVymazu"`
	DatumZapisu          string `json:"datumZapisu"`
	Text                 string `json:"text"`
	VznikZastavnihoPrava string `json:"vznikZastavnihoPrava"`
	ZanikZastavnihoPrava string `json:"zanikZastavnihoPrava"`
}

type ZaznamCeu struct {
	Adresy           json.RawMessage `json:"adresy"`
	DatumAktualizace string          `json:"datumAktualizace"`
	DatumVzniku      string          `json:"datumVzniku"`
	DatumZaniku      string          `json:"datumZaniku"`
	Dic              string          `json:"dic"`
	FinancniUrad     string          `json:"financniUrad"`
	Ico              string          `json:"ico"`
	JmenoPrijmeni    string          `json:"jmenoPrijmeni"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	PravniForma      string          `json:"pravniForma"`
	PravniFormaRos   string          `json:"pravniFormaRos"`
	Sidlo            json.RawMessage `json:"sidlo"`
	TypSubjektu      string          `json:"typSubjektu"`
	Upadek           json.RawMessage `json:"upadek"`
}

type ZaznamNrpzs struct {
	AngazovaneOsoby   json.RawMessage `json:"angazovaneOsoby"`
	DatumAktualizace  string          `json:"datumAktualizace"`
	DatumVzniku       string          `json:"datumVzniku"`
	DatumZaniku       string          `json:"datumZaniku"`
	Dic               string          `json:"dic"`
	DruhZarizeni      string          `json:"druhZarizeni"`
	FinancniUrad      string          `json:"financniUrad"`
	Ico               string          `json:"ico"`
	Kontakty          json.RawMessage `json:"kontakty"`
	ObchodniJmeno     string          `json:"obchodniJmeno"`
	PoradoveCisloPrac string          `json:"poradoveCisloPrac"`
	PoradoveCisloZar  string          `json:"poradoveCisloZar"`
	PravniForma       string          `json:"pravniForma"`
	PravniFormaRos    string          `json:"pravniFormaRos"`
	PrimarniZaznam    bool            `json:"primarniZaznam"`
	Sidlo             json.RawMessage `json:"sidlo"`
	TypSubjektu       string          `json:"typSubjektu"`
	TypZrizovatele    string          `json:"typZrizovatele"`
}

type ZaznamRcns struct {
	AdresySubjektu   json.RawMessage `json:"adresySubjektu"`
	DatumAktualizace string          `json:"datumAktualizace"`
	DatumVzniku      string          `json:"datumVzniku"`
	DatumZaniku      string          `json:"datumZaniku"`
	Dic              string          `json:"dic"`
	FinancniUrad     string          `json:"financniUrad"`
	Ico              string          `json:"ico"`
	KonkurzniSpravci json.RawMessage `json:"konkurzniSpravci"`
	Likvidatori      json.RawMessage `json:"likvidatori"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	Opatrovnici      json.RawMessage `json:"opatrovnici"`
	PlatnostOd       string          `json:"platnostOd"`
	PravniForma      string          `json:"pravniForma"`
	PravniFormaRos   string          `json:"pravniFormaRos"`
	PrimarniZaznam   bool            `json:"primarniZaznam"`
	Registrace       json.RawMessage `json:"registrace"`
	Sidlo            json.RawMessage `json:"sidlo"`
	Stat             string          `json:"stat"`
	StatutarniOrgan  json.RawMessage `json:"statutarniOrgan"`
	TypSubjektu      string          `json:"typSubjektu"`
	ZdrojId          string          `json:"zdrojId"`
	ZpusobJednani    json.RawMessage `json:"zpusobJednani"`
}

type ZaznamRcnsZaklad struct {
	AdresySubjektu   json.RawMessage `json:"adresySubjektu"`
	DatumAktualizace string          `json:"datumAktualizace"`
	DatumVzniku      string          `json:"datumVzniku"`
	DatumZaniku      string          `json:"datumZaniku"`
	Dic              string          `json:"dic"`
	FinancniUrad     string          `json:"financniUrad"`
	Ico              string          `json:"ico"`
	ObchodniJmeno    string          `json:"obchodniJmeno"`
	PlatnostOd       string          `json:"platnostOd"`
	PravniForma      string          `json:"pravniForma"`
	PravniFormaRos   string          `json:"pravniFormaRos"`
	PrimarniZaznam   bool            `json:"primarniZaznam"`
	Registrace       json.RawMessage `json:"registrace"`
	Sidlo            json.RawMessage `json:"sidlo"`
	Stat             string          `json:"stat"`
	TypSubjektu      string          `json:"typSubjektu"`
	ZdrojId          string          `json:"zdrojId"`
	ZpusobJednani    json.RawMessage `json:"zpusobJednani"`
}

type ZaznamRes struct {
	CzNace                 json.RawMessage `json:"czNace"`
	CzNace2008             json.RawMessage `json:"czNace2008"`
	CzNacePrevazujici      string          `json:"czNacePrevazujici"`
	CzNacePrevazujici2008  string          `json:"czNacePrevazujici2008"`
	DatumAktualizace       string          `json:"datumAktualizace"`
	DatumVzniku            string          `json:"datumVzniku"`
	DatumZaniku            string          `json:"datumZaniku"`
	Dic                    string          `json:"dic"`
	DoplnkovePravniFormy   json.RawMessage `json:"doplnkovePravniFormy"`
	FinancniUrad           string          `json:"financniUrad"`
	Ico                    string          `json:"ico"`
	ObchodniJmeno          string          `json:"obchodniJmeno"`
	OkresNutsLau           string          `json:"okresNutsLau"`
	PravniForma            string          `json:"pravniForma"`
	PravniFormaRos         string          `json:"pravniFormaRos"`
	PrimarniZaznam         bool            `json:"primarniZaznam"`
	Sidlo                  json.RawMessage `json:"sidlo"`
	StatistickeUdaje       json.RawMessage `json:"statistickeUdaje"`
	ZakladniUzemniJednotka string          `json:"zakladniUzemniJednotka"`
}

type ZaznamRos struct {
	DatoveSchranky     json.RawMessage `json:"datoveSchranky"`
	DatumAktualizace   string          `json:"datumAktualizace"`
	DatumVzniku        string          `json:"datumVzniku"`
	DatumZaniku        string          `json:"datumZaniku"`
	EvidenceAgendy     json.RawMessage `json:"evidenceAgendy"`
	Ico                string          `json:"ico"`
	InsolvencniSpravci json.RawMessage `json:"insolvencniSpravci"`
	KontaktniUdaje     json.RawMessage `json:"kontaktniUdaje"`
	Likvidatori        json.RawMessage `json:"likvidatori"`
	NuceniSpravci      json.RawMessage `json:"nuceniSpravci"`
	Opatrovnici        json.RawMessage `json:"opatrovnici"`
	PravniFormaRos     json.RawMessage `json:"pravniFormaRos"`
	PravniStavRos      json.RawMessage `json:"pravniStavRos"`
	Provozovny         json.RawMessage `json:"provozovny"`
	StatutarniOrgany   json.RawMessage `json:"statutarniOrgany"`
	StavSubjektu       string          `json:"stavSubjektu"`
}

type ZaznamRosZaklad struct {
	DatoveSchranky   json.RawMessage `json:"datoveSchranky"`
	DatumAktualizace string          `json:"datumAktualizace"`
	DatumVzniku      string          `json:"datumVzniku"`
	DatumZaniku      string          `json:"datumZaniku"`
	EvidenceAgendy   json.RawMessage `json:"evidenceAgendy"`
	Ico              string          `json:"ico"`
	KontaktniUdaje   json.RawMessage `json:"kontaktniUdaje"`
	PravniFormaRos   json.RawMessage `json:"pravniFormaRos"`
	PravniStavRos    json.RawMessage `json:"pravniStavRos"`
	Provozovny       json.RawMessage `json:"provozovny"`
	StavSubjektu     string          `json:"stavSubjektu"`
}

type ZaznamRpsh struct {
	AngazovaneOsoby      json.RawMessage `json:"angazovaneOsoby"`
	CisloRegistrace      string          `json:"cisloRegistrace"`
	DatumAktualizace     string          `json:"datumAktualizace"`
	DatumVzniku          string          `json:"datumVzniku"`
	DatumZaniku          string          `json:"datumZaniku"`
	Dic                  string          `json:"dic"`
	FinancniUrad         string          `json:"financniUrad"`
	Ico                  string          `json:"ico"`
	ObchodniJmeno        string          `json:"obchodniJmeno"`
	ObchodniJmenoZkratka string          `json:"obchodniJmenoZkratka"`
	PravniForma          string          `json:"pravniForma"`
	PravniFormaRos       string          `json:"pravniFormaRos"`
	PrimarniZaznam       bool            `json:"primarniZaznam"`
	Sidlo                json.RawMessage `json:"sidlo"`
	StatutarniOrgan      json.RawMessage `json:"statutarniOrgan"`
	StavSubjektu         json.RawMessage `json:"stavSubjektu"`
	TypSubjektu          string          `json:"typSubjektu"`
	ZmenaStanov          json.RawMessage `json:"zmenaStanov"`
}

type ZaznamRs struct {
	AngazovanaOsoba       json.RawMessage `json:"angazovanaOsoba"`
	AngazovanySubjekt     json.RawMessage `json:"angazovanySubjekt"`
	DatumAktualizace      string          `json:"datumAktualizace"`
	DatumVzniku           string          `json:"datumVzniku"`
	DatumZaniku           string          `json:"datumZaniku"`
	Dic                   string          `json:"dic"`
	FinancniUrad          string          `json:"financniUrad"`
	Ico                   string          `json:"ico"`
	Kontakty              json.RawMessage `json:"kontakty"`
	ObchodniJmeno         string          `json:"obchodniJmeno"`
	ObchodniJmenoZkracene string          `json:"obchodniJmenoZkracene"`
	PravniForma           string          `json:"pravniForma"`
	PravniFormaRos        string          `json:"pravniFormaRos"`
	PrimarniZaznam        bool            `json:"primarniZaznam"`
	Redizo                string          `json:"redizo"`
	Sidlo                 json.RawMessage `json:"sidlo"`
	SkolyAZarizeni        json.RawMessage `json:"skolyAZarizeni"`
	TypSubjektu           string          `json:"typSubjektu"`
}

type ZaznamRsZaklad struct {
	DatumAktualizace      string          `json:"datumAktualizace"`
	DatumVzniku           string          `json:"datumVzniku"`
	DatumZaniku           string          `json:"datumZaniku"`
	Dic                   string          `json:"dic"`
	FinancniUrad          string          `json:"financniUrad"`
	Ico                   string          `json:"ico"`
	Kontakty              json.RawMessage `json:"kontakty"`
	ObchodniJmeno         string          `json:"obchodniJmeno"`
	ObchodniJmenoZkracene string          `json:"obchodniJmenoZkracene"`
	PravniForma           string          `json:"pravniForma"`
	PravniFormaRos        string          `json:"pravniFormaRos"`
	PrimarniZaznam        bool            `json:"primarniZaznam"`
	Redizo                string          `json:"redizo"`
	Sidlo                 json.RawMessage `json:"sidlo"`
	SkolyAZarizeni        json.RawMessage `json:"skolyAZarizeni"`
	TypSubjektu           string          `json:"typSubjektu"`
}

type ZaznamRzp struct {
	AdresySubjektu      json.RawMessage `json:"adresySubjektu"`
	AngazovaneOsoby     json.RawMessage `json:"angazovaneOsoby"`
	DatumAktualizace    string          `json:"datumAktualizace"`
	DatumDoruceniVypisu string          `json:"datumDoruceniVypisu"`
	DatumVzniku         string          `json:"datumVzniku"`
	DatumZaniku         string          `json:"datumZaniku"`
	DatumZapisuVr       string          `json:"datumZapisuVr"`
	Dic                 string          `json:"dic"`
	FinancniUrad        string          `json:"financniUrad"`
	Ico                 string          `json:"ico"`
	InsolvencniRizeni   json.RawMessage `json:"insolvencniRizeni"`
	KodStatu            string          `json:"kodStatu"`
	ObchodniJmeno       string          `json:"obchodniJmeno"`
	OrganizacniSlozka   string          `json:"organizacniSlozka"`
	OsobaPodnikatel     json.RawMessage `json:"osobaPodnikatel"`
	PravniForma         string          `json:"pravniForma"`
	PravniFormaRos      string          `json:"pravniFormaRos"`
	PrimarniZaznam      bool            `json:"primarniZaznam"`
	ProvozovnyStav      json.RawMessage `json:"provozovnyStav"`
	Sidlo               json.RawMessage `json:"sidlo"`
	SouvisejiciSubjekty json.RawMessage `json:"souvisejiciSubjekty"`
	TypSubjektu         string          `json:"typSubjektu"`
	ZivnostenskyUrad    string          `json:"zivnostenskyUrad"`
	Zivnosti            json.RawMessage `json:"zivnosti"`
	ZivnostiStav        json.RawMessage `json:"zivnostiStav"`
}

type ZaznamRzpZaklad struct {
	AdresySubjektu      json.RawMessage `json:"adresySubjektu"`
	DatumAktualizace    string          `json:"datumAktualizace"`
	DatumDoruceniVypisu string          `json:"datumDoruceniVypisu"`
	DatumVzniku         string          `json:"datumVzniku"`
	DatumZaniku         string          `json:"datumZaniku"`
	DatumZapisuVr       string          `json:"datumZapisuVr"`
	Dic                 string          `json:"dic"`
	FinancniUrad        string          `json:"financniUrad"`
	Ico                 string          `json:"ico"`
	InsolvencniRizeni   json.RawMessage `json:"insolvencniRizeni"`
	KodStatu            string          `json:"kodStatu"`
	ObchodniJmeno       string          `json:"obchodniJmeno"`
	OrganizacniSlozka   string          `json:"organizacniSlozka"`
	PravniForma         string          `json:"pravniForma"`
	PravniFormaRos      string          `json:"pravniFormaRos"`
	PrimarniZaznam      bool            `json:"primarniZaznam"`
	ProvozovnyStav      json.RawMessage `json:"provozovnyStav"`
	Sidlo               json.RawMessage `json:"sidlo"`
	TypSubjektu         string          `json:"typSubjektu"`
	ZivnostenskyUrad    string          `json:"zivnostenskyUrad"`
	ZivnostiStav        json.RawMessage `json:"zivnostiStav"`
}

type ZaznamSzr struct {
	Ezp json.RawMessage `json:"ezp"`
}

type ZaznamVr struct {
	Adresy                json.RawMessage `json:"adresy"`
	Akcie                 json.RawMessage `json:"akcie"`
	Akcionari             json.RawMessage `json:"akcionari"`
	Cinnosti              json.RawMessage `json:"cinnosti"`
	DatumAktualizace      string          `json:"datumAktualizace"`
	DatumVymazu           string          `json:"datumVymazu"`
	DatumVzniku           json.RawMessage `json:"datumVzniku"`
	DatumZapisu           string          `json:"datumZapisu"`
	Exekuce               json.RawMessage `json:"exekuce"`
	FinancniUrad          string          `json:"financniUrad"`
	Ico                   json.RawMessage `json:"ico"`
	Insolvence            json.RawMessage `json:"insolvence"`
	KategorieZO           json.RawMessage `json:"kategorieZO"`
	Konkursy              json.RawMessage `json:"konkursy"`
	NazevNejvyssihoOrganu json.RawMessage `json:"nazevNejvyssihoOrganu"`
	ObchodniJmeno         json.RawMessage `json:"obchodniJmeno"`
	ObchodniJmenoCizi     json.RawMessage `json:"obchodniJmenoCizi"`
	OdstepneZavody        json.RawMessage `json:"odstepneZavody"`
	OstatniOrgany         json.RawMessage `json:"ostatniOrgany"`
	OstatniSkutecnosti    json.RawMessage `json:"ostatniSkutecnosti"`
	Podnikatel            json.RawMessage `json:"podnikatel"`
	PravniDuvodVymazu     json.RawMessage `json:"pravniDuvodVymazu"`
	PravniForma           json.RawMessage `json:"pravniForma"`
	PrimarniZaznam        bool            `json:"primarniZaznam"`
	Rejstrik              string          `json:"rejstrik"`
	SpisovaZnacka         json.RawMessage `json:"spisovaZnacka"`
	Spolecnici            json.RawMessage `json:"spolecnici"`
	StatutarniOrgany      json.RawMessage `json:"statutarniOrgany"`
	StavSubjektu          string          `json:"stavSubjektu"`
	Vklady                json.RawMessage `json:"vklady"`
	ZakladniKapital       json.RawMessage `json:"zakladniKapital"`
	ZpusobRizeni          json.RawMessage `json:"zpusobRizeni"`
}

type ZaznamVrZaklad struct {
	Adresy                json.RawMessage `json:"adresy"`
	Akcie                 json.RawMessage `json:"akcie"`
	Cinnosti              json.RawMessage `json:"cinnosti"`
	DatumAktualizace      string          `json:"datumAktualizace"`
	DatumVymazu           string          `json:"datumVymazu"`
	DatumVzniku           json.RawMessage `json:"datumVzniku"`
	DatumZapisu           string          `json:"datumZapisu"`
	Exekuce               json.RawMessage `json:"exekuce"`
	FinancniUrad          string          `json:"financniUrad"`
	Ico                   json.RawMessage `json:"ico"`
	KategorieZO           json.RawMessage `json:"kategorieZO"`
	NazevNejvyssihoOrganu json.RawMessage `json:"nazevNejvyssihoOrganu"`
	ObchodniJmeno         json.RawMessage `json:"obchodniJmeno"`
	ObchodniJmenoCizi     json.RawMessage `json:"obchodniJmenoCizi"`
	OstatniSkutecnosti    json.RawMessage `json:"ostatniSkutecnosti"`
	PravniDuvodVymazu     json.RawMessage `json:"pravniDuvodVymazu"`
	PravniForma           json.RawMessage `json:"pravniForma"`
	PrimarniZaznam        bool            `json:"primarniZaznam"`
	Rejstrik              string          `json:"rejstrik"`
	SpisovaZnacka         json.RawMessage `json:"spisovaZnacka"`
	StavSubjektu          string          `json:"stavSubjektu"`
	Vklady                json.RawMessage `json:"vklady"`
	ZakladniKapital       json.RawMessage `json:"zakladniKapital"`
	ZpusobRizeni          json.RawMessage `json:"zpusobRizeni"`
}

type Zivnost struct {
	DatumAktualizace            string          `json:"datumAktualizace"`
	DatumVzniku                 string          `json:"datumVzniku"`
	DatumZaniku                 string          `json:"datumZaniku"`
	DruhZivnosti                string          `json:"druhZivnosti"`
	OboryCinnosti               json.RawMessage `json:"oboryCinnosti"`
	OdpovedniZastupci           json.RawMessage `json:"odpovedniZastupci"`
	PlatnostDo                  string          `json:"platnostDo"`
	PodminkyProvozovaniZivnosti json.RawMessage `json:"podminkyProvozovaniZivnosti"`
	PozastaveniZivnosti         json.RawMessage `json:"pozastaveniZivnosti"`
	PredmetPodnikani            string          `json:"predmetPodnikani"`
	PreruseniZivnosti           json.RawMessage `json:"preruseniZivnosti"`
	Provozovny                  json.RawMessage `json:"provozovny"`
	ZivnostBezOz                json.RawMessage `json:"zivnostBezOz"`
}

type ZivnostBezOZ struct {
	PlatnostDo string `json:"platnostDo"`
	PlatnostOd string `json:"platnostOd"`
}

type ZivnostOborCinnosti struct {
	OborNazev  string `json:"oborNazev"`
	PlatnostDo string `json:"platnostDo"`
	PlatnostOd string `json:"platnostOd"`
}

type ZivnostPodminky struct {
	PlatnostDo string `json:"platnostDo"`
	PlatnostOd string `json:"platnostOd"`
	Podminka   string `json:"podminka"`
}

type ZivnostPreruseni struct {
	PlatnostDo string `json:"platnostDo"`
	PlatnostOd string `json:"platnostOd"`
}

type ZivnostProvozovnaPozastaveni struct {
	PlatnostDo        string `json:"platnostDo"`
	PlatnostOd        string `json:"platnostOd"`
	RozsahPozastaveni string `json:"rozsahPozastaveni"`
}

type ZivnostZaklad struct {
	DatumAktualizace            string          `json:"datumAktualizace"`
	DatumVzniku                 string          `json:"datumVzniku"`
	DatumZaniku                 string          `json:"datumZaniku"`
	DruhZivnosti                string          `json:"druhZivnosti"`
	PlatnostDo                  string          `json:"platnostDo"`
	PodminkyProvozovaniZivnosti json.RawMessage `json:"podminkyProvozovaniZivnosti"`
	PozastaveniZivnosti         json.RawMessage `json:"pozastaveniZivnosti"`
	PredmetPodnikani            string          `json:"predmetPodnikani"`
	PreruseniZivnosti           json.RawMessage `json:"preruseniZivnosti"`
	ZivnostBezOz                json.RawMessage `json:"zivnostBezOz"`
}

type ZivnostiRzpStav struct {
	PocetAktivnich     int `json:"pocetAktivnich"`
	PocetCelkem        int `json:"pocetCelkem"`
	PocetPozastavenych int `json:"pocetPozastavenych"`
	PocetPrerusenych   int `json:"pocetPrerusenych"`
	PocetZaniklych     int `json:"pocetZaniklych"`
}

type ZmenaStanov struct {
	DatumZmeny string `json:"datumZmeny"`
}

type ZpusobJednani struct {
	PlatnostDo string `json:"platnostDo"`
	PlatnostOd string `json:"platnostOd"`
	Popis      string `json:"popis"`
}

type ZpusobRizeniVr struct {
	DatumVymazu string `json:"datumVymazu"`
	DatumZapisu string `json:"datumZapisu"`
	Typ         string `json:"typ"`
}
