// Copyright 2026 patrik-zita. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"ares-pp-cli/internal/cli"
	"ares-pp-cli/internal/client"
	"ares-pp-cli/internal/config"
	"ares-pp-cli/internal/mcp/cobratree"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("ciselniky-nazevniky_vyhledej-ciselnik",
			mcplib.WithDescription("Vyhledání číselníků používaných v IS ARES podle komplexního filtru. Optional: kodCiselniku, pocet, razeni (plus 2 more). Returns the new CiselnikyNazevnikSeznam."),
			mcplib.WithString("kodCiselniku", mcplib.Description("Kód číselníku")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithString("zdrojCiselniku", mcplib.Description("Zdroj/oblast číselníku - kód (ciselnikKod: TypZdrojeAres, zdroj:com)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ciselniky-nazevniky/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "kodCiselniku", WireName: "kodCiselniku", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}, {PublicName: "zdrojCiselniku", WireName: "zdrojCiselniku", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty_vrat-ekonomicky-subjekt",
			mcplib.WithDescription("Vyhledání ekonomického subjektu ARES podle zadaného iča. Required: ico. Returns the EkonomickySubjekt."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty_vyhledej",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektů ARES podle komplexního filtru. Optional: czNace, financniUrad, ico (plus 7 more). Returns the new EkonomickeSubjektySeznam."),
			mcplib.WithString("czNace", mcplib.Description("Cz nace")),
			mcplib.WithString("financniUrad", mcplib.Description("Financni urad")),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithString("obchodniJmeno", mcplib.Description("Obchodní jméno ekonomického subjektu")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("pravniForma", mcplib.Description("Pravni forma")),
			mcplib.WithString("pravniFormaRos", mcplib.Description("Pravni forma ros")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithString("sidlo", mcplib.Description("Adresa")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "czNace", WireName: "czNace", Location: "body"}, {PublicName: "financniUrad", WireName: "financniUrad", Location: "body"}, {PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "obchodniJmeno", WireName: "obchodniJmeno", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "pravniForma", WireName: "pravniForma", Location: "body"}, {PublicName: "pravniFormaRos", WireName: "pravniFormaRos", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "sidlo", WireName: "sidlo", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-ceu_vrat-ekonomicky-subjekt-ceu",
			mcplib.WithDescription("Vyhledání konkrétního úpadce ze zdroje CEÚ. Required: ico. Returns the EkonomickySubjektCeu."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-ceu/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-ceu_vyhledej-seznam-ekonomickych-subjektu-ceu",
			mcplib.WithDescription("Vyhledání seznamu úpadců ze zdroje CEÚ. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyCeuSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-ceu/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-notifikace_vrat-notifikacni-davku",
			mcplib.WithDescription("Vyhledání konkrétní notifikační dávky zdroje ARES podle vstupcách parametrů (zdroj, číslo notifikační dávky). Required: datovyZdroj, cisloDavky. Returns the NotifikacniDavkaZaznam."),
			mcplib.WithString("datovyZdroj", mcplib.Required(), mcplib.Description("Datovy zdroj")),
			mcplib.WithNumber("cisloDavky", mcplib.Required(), mcplib.Description("Cislo davky")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-notifikace/datovy-zdroj/{datovyZdroj}/cislo-davky/{cisloDavky}", true, false, nil, []mcpParamBinding{{PublicName: "datovyZdroj", WireName: "datovyZdroj", Location: "path"}, {PublicName: "cisloDavky", WireName: "cisloDavky", Location: "path"}}, []string{"datovyZdroj", "cisloDavky"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-notifikace_vyhledej-seznam-notifikacnich-davek",
			mcplib.WithDescription("Vyhledání seznamu notifikačních dávek ekonomických subjektů ARES podle zvoleného filtru. Optional: datovyZdroj. Returns the new SeznamNotifikacnichDavek."),
			mcplib.WithString("datovyZdroj", mcplib.Description("Datový zdroj notifikační dávky - kód (ciselnikKod: TypZdrojeAres, zdroj:com) Podporované zdroje")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-notifikace/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "datovyZdroj", WireName: "datovyZdroj", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-nrpzs_vrat-ekonomicky-subjekt-nrpzs",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje NRPZS. Required: ico. Returns the EkonomickySubjektNrpzs."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-nrpzs/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-nrpzs_vyhledej-seznam-ekonomickych-subjektu-nrpzs",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje NRPZS. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyNrpzsSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-nrpzs/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-rcns_vrat-ekonomicky-subjekt-rcns",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje RCNS. Required: ico. Returns the EkonomickySubjektRcns."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-rcns/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-rcns_vyhledej-seznam-ekonomickych-subjektu-rcns",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje RCNS. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyRcnsSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-rcns/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-res_vrat-ekonomicky-subjekt-res",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje RES. Required: ico. Returns the EkonomickySubjektRes."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-res/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-res_vyhledej-seznam-ekonomickych-subjektu-res",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje RES. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyResSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-res/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-ros_vrat-ekonomicky-subjekt-ros",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje ROS. Required: ico. Returns the EkonomickySubjektRos."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-ros/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-ros_vyhledej-seznam-ekonomickych-subjektu-ros",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje ROS. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyRosSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-ros/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-rpsh_vrat-ekonomicky-subjekt-rpsh",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje RPSH. Required: ico. Returns the EkonomickySubjektRpsh."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-rpsh/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-rpsh_vyhledej-seznam-ekonomickych-subjektu-rpsh",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje RPSH. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyRpshSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-rpsh/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-rs_vrat-ekonomicky-subjekt-rs",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje RŠ. Required: ico. Returns the EkonomickySubjektRs."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-rs/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-rs_vyhledej-seznam-ekonomickych-subjektu-rs",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje RŠ. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyRsSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-rs/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-rzp_vrat-ekonomicky-subjekt-rzp",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje RŽP. Required: ico. Returns the EkonomickySubjektRzp."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-rzp/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-rzp_vyhledej-seznam-ekonomickych-subjektu-rzp",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje RŽP. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyRzpSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-rzp/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-szr_vrat-ekonomicky-subjekt-szr",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje SZR - subregistr EZP. Required: ico. Returns the EkonomickySubjektSzr."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-szr/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-szr_vyhledej-seznam-ekonomickych-subjektu-szr",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje SZR - subregistr EZP. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektySzrSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-szr/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-vr_vrat-ekonomicky-subjekt-vr",
			mcplib.WithDescription("Vyhledání konkrétního ekonomického subjektu ze zdroje VR. Required: ico. Returns the EkonomickySubjektVr."),
			mcplib.WithString("ico", mcplib.Required(), mcplib.Description("Ico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ekonomicke-subjekty-vr/{ico}", true, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "path"}}, []string{"ico"}),
	)
	s.AddTool(
		mcplib.NewTool("ekonomicke-subjekty-vr_vyhledej-seznam-ekonomickych-subjektu-vr",
			mcplib.WithDescription("Vyhledání seznamu ekonomických subjektu ze zdroje VR. Optional: ico, pocet, razeni (plus 1 more). Returns the new EkonomickeSubjektyVrSeznam."),
			mcplib.WithString("ico", mcplib.Description("Ico")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ekonomicke-subjekty-vr/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "ico", WireName: "ico", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("standardizovane-adresy_vyhledej",
			mcplib.WithDescription("Vyhledání seznamu standardizovaných adres RÚIAN podle komplexního filtru. Optional: cisloDomovni, cisloOrientacni, cisloOrientacniPismeno (plus 14 more). Returns the new StandardizovaneAdresySeznam."),
			mcplib.WithNumber("cisloDomovni", mcplib.Description("Číslo domovní")),
			mcplib.WithNumber("cisloOrientacni", mcplib.Description("Číslo orientační - číselná část")),
			mcplib.WithString("cisloOrientacniPismeno", mcplib.Description("Číslo orientační - písmenná část")),
			mcplib.WithNumber("kodAdresnihoMista", mcplib.Description("Kód adresního místa")),
			mcplib.WithNumber("kodCastiObce", mcplib.Description("Kód části obce")),
			mcplib.WithNumber("kodMestskehoCastiObvodu", mcplib.Description("Kód městské části statutárního města nebo Prahy")),
			mcplib.WithNumber("kodObce", mcplib.Description("Kód obce")),
			mcplib.WithNumber("kodUlice", mcplib.Description("Kód ulice, veřejného prostranství")),
			mcplib.WithString("nazevCastiObce", mcplib.Description("Název části obce")),
			mcplib.WithString("nazevMestskehoCastiObvodu", mcplib.Description("Název městské části statutárního města nebo Prahy")),
			mcplib.WithString("nazevObce", mcplib.Description("Název obce")),
			mcplib.WithString("nazevUlice", mcplib.Description("Název ulice, veřejného prostranství")),
			mcplib.WithNumber("pocet", mcplib.Description("Počet prvků k výstupu.")),
			mcplib.WithString("razeni", mcplib.Description("Razeni")),
			mcplib.WithNumber("start", mcplib.Description("Offset pro stránkování (poloha prvního vráceného prvku).")),
			mcplib.WithString("textovaAdresa", mcplib.Description("Nestrukturovaná adresa")),
			mcplib.WithString("typStandardizaceAdresy", mcplib.Description("Typ požadované standardizace - kód (číselník kod:TypStandardizaceAdresy) UPLNA_STANDARDIZACE, VYHOVUJICI_ADRESY")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/standardizovane-adresy/vyhledat", false, false, nil, []mcpParamBinding{{PublicName: "cisloDomovni", WireName: "cisloDomovni", Location: "body"}, {PublicName: "cisloOrientacni", WireName: "cisloOrientacni", Location: "body"}, {PublicName: "cisloOrientacniPismeno", WireName: "cisloOrientacniPismeno", Location: "body"}, {PublicName: "kodAdresnihoMista", WireName: "kodAdresnihoMista", Location: "body"}, {PublicName: "kodCastiObce", WireName: "kodCastiObce", Location: "body"}, {PublicName: "kodMestskehoCastiObvodu", WireName: "kodMestskehoCastiObvodu", Location: "body"}, {PublicName: "kodObce", WireName: "kodObce", Location: "body"}, {PublicName: "kodUlice", WireName: "kodUlice", Location: "body"}, {PublicName: "nazevCastiObce", WireName: "nazevCastiObce", Location: "body"}, {PublicName: "nazevMestskehoCastiObvodu", WireName: "nazevMestskehoCastiObvodu", Location: "body"}, {PublicName: "nazevObce", WireName: "nazevObce", Location: "body"}, {PublicName: "nazevUlice", WireName: "nazevUlice", Location: "body"}, {PublicName: "pocet", WireName: "pocet", Location: "body"}, {PublicName: "razeni", WireName: "razeni", Location: "body"}, {PublicName: "start", WireName: "start", Location: "body"}, {PublicName: "textovaAdresa", WireName: "textovaAdresa", Location: "body"}, {PublicName: "typStandardizaceAdresy", WireName: "typStandardizaceAdresy", Location: "body"}}, []string{}),
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'ares-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'ares-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "ares-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "ares-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "ares",
		"description": "REST rozhraní systému ARES",
		"archetype":   "generic",
		"tool_count":  26,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion ares-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name":        "ciselniky-nazevniky",
				"description": "ciselniky-nazevniky operations",
				"endpoints":   []string{"vyhledej-ciselnik"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty",
				"description": "ekonomicke-subjekty operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt", "vyhledej"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-ceu",
				"description": "ekonomicke-subjekty-ceu operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-ceu", "vyhledej-seznam-ekonomickych-subjektu-ceu"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-notifikace",
				"description": "ekonomicke-subjekty-notifikace operations",
				"endpoints":   []string{"vrat-notifikacni-davku", "vyhledej-seznam-notifikacnich-davek"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-nrpzs",
				"description": "ekonomicke-subjekty-nrpzs operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-nrpzs", "vyhledej-seznam-ekonomickych-subjektu-nrpzs"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-rcns",
				"description": "ekonomicke-subjekty-rcns operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-rcns", "vyhledej-seznam-ekonomickych-subjektu-rcns"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-res",
				"description": "ekonomicke-subjekty-res operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-res", "vyhledej-seznam-ekonomickych-subjektu-res"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-ros",
				"description": "ekonomicke-subjekty-ros operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-ros", "vyhledej-seznam-ekonomickych-subjektu-ros"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-rpsh",
				"description": "ekonomicke-subjekty-rpsh operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-rpsh", "vyhledej-seznam-ekonomickych-subjektu-rpsh"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-rs",
				"description": "ekonomicke-subjekty-rs operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-rs", "vyhledej-seznam-ekonomickych-subjektu-rs"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-rzp",
				"description": "ekonomicke-subjekty-rzp operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-rzp", "vyhledej-seznam-ekonomickych-subjektu-rzp"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-szr",
				"description": "ekonomicke-subjekty-szr operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-szr", "vyhledej-seznam-ekonomickych-subjektu-szr"},
				"searchable":  true,
			},
			{
				"name":        "ekonomicke-subjekty-vr",
				"description": "ekonomicke-subjekty-vr operations",
				"endpoints":   []string{"vrat-ekonomicky-subjekt-vr", "vyhledej-seznam-ekonomickych-subjektu-vr"},
				"searchable":  true,
			},
			{
				"name":        "standardizovane-adresy",
				"description": "standardizovane-adresy operations",
				"endpoints":   []string{"vyhledej"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Bulk enrich", "command": "enrich", "description": "Pipe a list of IČOs and get one enriched company record per line for invoicing or CRM import.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Portfolio watchlist", "command": "portfolio", "description": "Keep a local watchlist of client and supplier IČOs and bulk-refresh them into the store.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Change diffing", "command": "changes", "description": "Report name, address, legal-form, and status changes across tracked subjects since a point in time.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Insolvency watch", "command": "insolvency-watch", "description": "Flag portfolio members that newly appear among CEÚ insolvency subjects.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Offline search", "command": "search", "description": "Full-text search over synced company names and addresses with no network call.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Offline IČO validation", "command": "validate", "description": "Validate Czech IČO checksums in bulk with zero API calls.", "rationale": "", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Bulk enrich", "insight": ""},
			{"topic": "Portfolio watchlist", "insight": ""},
			{"topic": "Change diffing", "insight": ""},
			{"topic": "Insolvency watch", "insight": ""},
			{"topic": "Offline search", "insight": ""},
			{"topic": "Offline IČO validation", "insight": ""},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
