// Copyright 2026 patrik-zita. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEkonomickeSubjektyVrVratEkonomickySubjektVrCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "vrat-ekonomicky-subjekt-vr <ico>",
		Aliases:     []string{"get"},
		Short:       "Vyhledání konkrétního ekonomického subjektu ze zdroje VR",
		Example:     "  ares-pp-cli ekonomicke-subjekty-vr vrat-ekonomicky-subjekt-vr example-value",
		Annotations: map[string]string{"pp:endpoint": "ekonomicke-subjekty-vr.vrat-ekonomicky-subjekt-vr", "pp:method": "GET", "pp:path": "/ekonomicke-subjekty-vr/{ico}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/ekonomicke-subjekty-vr/{ico}"
			path = replacePathParam(path, "ico", args[0])
			params := map[string]string{}
			data, err := c.Get(cmd.Context(), path, params)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}

	return cmd
}
