// Copyright 2026 patrik-zita. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEkonomickeSubjektyRosCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "ekonomicke-subjekty-ros",
		Short:  "ekonomicke-subjekty-ros operations",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEkonomickeSubjektyRosVratEkonomickySubjektRosCmd(flags))
	cmd.AddCommand(newEkonomickeSubjektyRosVyhledejSeznamEkonomickychSubjektuRosCmd(flags))
	return cmd
}
