// Copyright 2026 patrik-zita. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newEkonomickeSubjektyVyhledejCmd(flags *rootFlags) *cobra.Command {
	var bodyCzNace string
	var bodyFinancniUrad string
	var bodyIco string
	var bodyObchodniJmeno string
	var bodyPocet int
	var bodyPravniForma string
	var bodyPravniFormaRos string
	var bodyRazeni string
	var bodySidloCisloDomovni int
	var bodySidloCisloOrientacni int
	var bodySidloCisloOrientacniPismeno string
	var bodySidloKodCastiObce int
	var bodySidloKodMestskeCastiObvodu int
	var bodySidloKodObce int
	var bodySidloKodSpravnihoObvodu int
	var bodySidloKodUlice int
	var bodySidloTextovaAdresa string
	var bodyStart int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "vyhledej",
		Aliases:     []string{"create"},
		Short:       "Vyhledání seznamu ekonomických subjektů ARES podle komplexního filtru",
		Example:     "  ares-pp-cli ekonomicke-subjekty vyhledej",
		Annotations: map[string]string{"pp:endpoint": "ekonomicke-subjekty.vyhledej", "pp:method": "POST", "pp:path": "/ekonomicke-subjekty/vyhledat"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/ekonomicke-subjekty/vyhledat"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCzNace != "" {
					var parsedCzNace any
					if err := json.Unmarshal([]byte(bodyCzNace), &parsedCzNace); err != nil {
						return fmt.Errorf("parsing --cz-nace JSON: %w", err)
					}
					body["czNace"] = parsedCzNace
				}
				if bodyFinancniUrad != "" {
					var parsedFinancniUrad any
					if err := json.Unmarshal([]byte(bodyFinancniUrad), &parsedFinancniUrad); err != nil {
						return fmt.Errorf("parsing --financni-urad JSON: %w", err)
					}
					body["financniUrad"] = parsedFinancniUrad
				}
				if bodyIco != "" {
					var parsedIco any
					if err := json.Unmarshal([]byte(bodyIco), &parsedIco); err != nil {
						return fmt.Errorf("parsing --ico JSON: %w", err)
					}
					body["ico"] = parsedIco
				}
				if bodyObchodniJmeno != "" {
					body["obchodniJmeno"] = bodyObchodniJmeno
				}
				if bodyPocet != 0 {
					body["pocet"] = bodyPocet
				}
				if bodyPravniForma != "" {
					var parsedPravniForma any
					if err := json.Unmarshal([]byte(bodyPravniForma), &parsedPravniForma); err != nil {
						return fmt.Errorf("parsing --pravni-forma JSON: %w", err)
					}
					body["pravniForma"] = parsedPravniForma
				}
				if bodyPravniFormaRos != "" {
					var parsedPravniFormaRos any
					if err := json.Unmarshal([]byte(bodyPravniFormaRos), &parsedPravniFormaRos); err != nil {
						return fmt.Errorf("parsing --pravni-forma-ros JSON: %w", err)
					}
					body["pravniFormaRos"] = parsedPravniFormaRos
				}
				if bodyRazeni != "" {
					var parsedRazeni any
					if err := json.Unmarshal([]byte(bodyRazeni), &parsedRazeni); err != nil {
						return fmt.Errorf("parsing --razeni JSON: %w", err)
					}
					body["razeni"] = parsedRazeni
				}
				{
					nestedSidlo := map[string]any{}
					if bodySidloCisloDomovni != 0 {
						nestedSidlo["cisloDomovni"] = bodySidloCisloDomovni
					}
					if bodySidloCisloOrientacni != 0 {
						nestedSidlo["cisloOrientacni"] = bodySidloCisloOrientacni
					}
					if bodySidloCisloOrientacniPismeno != "" {
						nestedSidlo["cisloOrientacniPismeno"] = bodySidloCisloOrientacniPismeno
					}
					if bodySidloKodCastiObce != 0 {
						nestedSidlo["kodCastiObce"] = bodySidloKodCastiObce
					}
					if bodySidloKodMestskeCastiObvodu != 0 {
						nestedSidlo["kodMestskeCastiObvodu"] = bodySidloKodMestskeCastiObvodu
					}
					if bodySidloKodObce != 0 {
						nestedSidlo["kodObce"] = bodySidloKodObce
					}
					if bodySidloKodSpravnihoObvodu != 0 {
						nestedSidlo["kodSpravnihoObvodu"] = bodySidloKodSpravnihoObvodu
					}
					if bodySidloKodUlice != 0 {
						nestedSidlo["kodUlice"] = bodySidloKodUlice
					}
					if bodySidloTextovaAdresa != "" {
						nestedSidlo["textovaAdresa"] = bodySidloTextovaAdresa
					}
					if len(nestedSidlo) > 0 {
						body["sidlo"] = nestedSidlo
					}
				}
				if bodyStart != 0 {
					body["start"] = bodyStart
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "ekonomicke-subjekty", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ekonomicke-subjekty", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ekonomicke-subjekty", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ekonomicke-subjekty", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "ekonomicke-subjekty",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ekonomicke-subjekty", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ekonomicke-subjekty", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyCzNace, "cz-nace", "", "Cz nace")
	cmd.Flags().StringVar(&bodyFinancniUrad, "financni-urad", "", "Financni urad")
	cmd.Flags().StringVar(&bodyIco, "ico", "", "Ico")
	cmd.Flags().StringVar(&bodyObchodniJmeno, "obchodni-jmeno", "", "Obchodní jméno ekonomického subjektu")
	cmd.Flags().IntVar(&bodyPocet, "pocet", 0, "Počet prvků k výstupu.")
	cmd.Flags().StringVar(&bodyPravniForma, "pravni-forma", "", "Pravni forma")
	cmd.Flags().StringVar(&bodyPravniFormaRos, "pravni-forma-ros", "", "Pravni forma ros")
	cmd.Flags().StringVar(&bodyRazeni, "razeni", "", "Razeni")
	cmd.Flags().IntVar(&bodySidloCisloDomovni, "sidlo-cislo-domovni", 0, "Číslo domovní")
	cmd.Flags().IntVar(&bodySidloCisloOrientacni, "sidlo-cislo-orientacni", 0, "Číslo orientační - číselná část")
	cmd.Flags().StringVar(&bodySidloCisloOrientacniPismeno, "sidlo-cislo-orientacni-pismeno", "", "Číslo orientační - písmenná část")
	cmd.Flags().IntVar(&bodySidloKodCastiObce, "sidlo-kod-casti-obce", 0, "Kód časti obce")
	cmd.Flags().IntVar(&bodySidloKodMestskeCastiObvodu, "sidlo-kod-mestske-casti-obvodu", 0, "Kód městské části statutárního města")
	cmd.Flags().IntVar(&bodySidloKodObce, "sidlo-kod-obce", 0, "Kód obce")
	cmd.Flags().IntVar(&bodySidloKodSpravnihoObvodu, "sidlo-kod-spravniho-obvodu", 0, "Kód správního obvodu Prahy")
	cmd.Flags().IntVar(&bodySidloKodUlice, "sidlo-kod-ulice", 0, "Kód ulice, veřejného prostranství ze zdroje")
	cmd.Flags().StringVar(&bodySidloTextovaAdresa, "sidlo-textova-adresa", "", "Nestrukturovaná adresa")
	cmd.Flags().IntVar(&bodyStart, "start", 0, "Offset pro stránkování (poloha prvního vráceného prvku).")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
