// Copyright 2026 patrik-zita. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newStandardizovaneAdresyPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyCisloDomovni int
	var bodyCisloOrientacni int
	var bodyCisloOrientacniPismeno string
	var bodyKodAdresnihoMista int
	var bodyKodCastiObce int
	var bodyKodMestskehoCastiObvodu int
	var bodyKodObce int
	var bodyKodUlice int
	var bodyNazevCastiObce string
	var bodyNazevMestskehoCastiObvodu string
	var bodyNazevObce string
	var bodyNazevUlice string
	var bodyPocet int
	var bodyRazeni string
	var bodyStart int
	var bodyTextovaAdresa string
	var bodyTypStandardizaceAdresy string

	cmd := &cobra.Command{
		Use:         "standardizovane-adresy",
		Short:       "Vyhledání seznamu standardizovaných adres RÚIAN podle komplexního filtru",
		Long:        "Shortcut for 'standardizovane-adresy vyhledej'. Vyhledání seznamu standardizovaných adres RÚIAN podle komplexního filtru",
		Example:     "  ares-pp-cli standardizovane-adresy",
		Annotations: map[string]string{"pp:endpoint": "standardizovane-adresy.vyhledej", "pp:method": "POST", "pp:path": "/standardizovane-adresy/vyhledat"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/standardizovane-adresy/vyhledat"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyCisloDomovni != 0 {
				body["cisloDomovni"] = bodyCisloDomovni
			}
			if bodyCisloOrientacni != 0 {
				body["cisloOrientacni"] = bodyCisloOrientacni
			}
			if bodyCisloOrientacniPismeno != "" {
				body["cisloOrientacniPismeno"] = bodyCisloOrientacniPismeno
			}
			if bodyKodAdresnihoMista != 0 {
				body["kodAdresnihoMista"] = bodyKodAdresnihoMista
			}
			if bodyKodCastiObce != 0 {
				body["kodCastiObce"] = bodyKodCastiObce
			}
			if bodyKodMestskehoCastiObvodu != 0 {
				body["kodMestskehoCastiObvodu"] = bodyKodMestskehoCastiObvodu
			}
			if bodyKodObce != 0 {
				body["kodObce"] = bodyKodObce
			}
			if bodyKodUlice != 0 {
				body["kodUlice"] = bodyKodUlice
			}
			if bodyNazevCastiObce != "" {
				body["nazevCastiObce"] = bodyNazevCastiObce
			}
			if bodyNazevMestskehoCastiObvodu != "" {
				body["nazevMestskehoCastiObvodu"] = bodyNazevMestskehoCastiObvodu
			}
			if bodyNazevObce != "" {
				body["nazevObce"] = bodyNazevObce
			}
			if bodyNazevUlice != "" {
				body["nazevUlice"] = bodyNazevUlice
			}
			if bodyPocet != 0 {
				body["pocet"] = bodyPocet
			}
			if bodyRazeni != "" {
				var parsedRazeni any
				if err := json.Unmarshal([]byte(bodyRazeni), &parsedRazeni); err != nil {
					return fmt.Errorf("parsing --razeni JSON: %w", err)
				}
				body["razeni"] = parsedRazeni
			}
			if bodyStart != 0 {
				body["start"] = bodyStart
			}
			if bodyTextovaAdresa != "" {
				body["textovaAdresa"] = bodyTextovaAdresa
			}
			if bodyTypStandardizaceAdresy != "" {
				body["typStandardizaceAdresy"] = bodyTypStandardizaceAdresy
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyCisloDomovni, "cislo-domovni", 0, "Číslo domovní")
	cmd.Flags().IntVar(&bodyCisloOrientacni, "cislo-orientacni", 0, "Číslo orientační - číselná část")
	cmd.Flags().StringVar(&bodyCisloOrientacniPismeno, "cislo-orientacni-pismeno", "", "Číslo orientační - písmenná část")
	cmd.Flags().IntVar(&bodyKodAdresnihoMista, "kod-adresniho-mista", 0, "Kód adresního místa")
	cmd.Flags().IntVar(&bodyKodCastiObce, "kod-casti-obce", 0, "Kód části obce")
	cmd.Flags().IntVar(&bodyKodMestskehoCastiObvodu, "kod-mestskeho-casti-obvodu", 0, "Kód městské části statutárního města nebo Prahy")
	cmd.Flags().IntVar(&bodyKodObce, "kod-obce", 0, "Kód obce")
	cmd.Flags().IntVar(&bodyKodUlice, "kod-ulice", 0, "Kód ulice, veřejného prostranství")
	cmd.Flags().StringVar(&bodyNazevCastiObce, "nazev-casti-obce", "", "Název části obce")
	cmd.Flags().StringVar(&bodyNazevMestskehoCastiObvodu, "nazev-mestskeho-casti-obvodu", "", "Název městské části statutárního města nebo Prahy")
	cmd.Flags().StringVar(&bodyNazevObce, "nazev-obce", "", "Název obce")
	cmd.Flags().StringVar(&bodyNazevUlice, "nazev-ulice", "", "Název ulice, veřejného prostranství")
	cmd.Flags().IntVar(&bodyPocet, "pocet", 0, "Počet prvků k výstupu.")
	cmd.Flags().StringVar(&bodyRazeni, "razeni", "", "Razeni")
	cmd.Flags().IntVar(&bodyStart, "start", 0, "Offset pro stránkování (poloha prvního vráceného prvku).")
	cmd.Flags().StringVar(&bodyTextovaAdresa, "textova-adresa", "", "Nestrukturovaná adresa")
	cmd.Flags().StringVar(&bodyTypStandardizaceAdresy, "typ-standardizace-adresy", "", "Typ požadované standardizace - kód (číselník kod:TypStandardizaceAdresy) UPLNA_STANDARDIZACE, VYHOVUJICI_ADRESY")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
