// Copyright 2026 patrik-zita. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCiselnikyNazevnikyPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyKodCiselniku string
	var bodyPocet int
	var bodyRazeni string
	var bodyStart int
	var bodyZdrojCiselniku string

	cmd := &cobra.Command{
		Use:         "ciselniky-nazevniky",
		Short:       "Vyhledání číselníků používaných v IS ARES podle komplexního filtru",
		Long:        "Shortcut for 'ciselniky-nazevniky vyhledej-ciselnik'. Vyhledání číselníků používaných v IS ARES podle komplexního filtru",
		Example:     "  ares-pp-cli ciselniky-nazevniky",
		Annotations: map[string]string{"pp:endpoint": "ciselniky-nazevniky.vyhledej-ciselnik", "pp:method": "POST", "pp:path": "/ciselniky-nazevniky/vyhledat"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/ciselniky-nazevniky/vyhledat"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyKodCiselniku != "" {
				body["kodCiselniku"] = bodyKodCiselniku
			}
			if bodyPocet != 0 {
				body["pocet"] = bodyPocet
			}
			if bodyRazeni != "" {
				var parsedRazeni any
				if err := json.Unmarshal([]byte(bodyRazeni), &parsedRazeni); err != nil {
					return fmt.Errorf("parsing --razeni JSON: %w", err)
				}
				body["razeni"] = parsedRazeni
			}
			if bodyStart != 0 {
				body["start"] = bodyStart
			}
			if bodyZdrojCiselniku != "" {
				body["zdrojCiselniku"] = bodyZdrojCiselniku
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyKodCiselniku, "kod-ciselniku", "", "Kód číselníku")
	cmd.Flags().IntVar(&bodyPocet, "pocet", 0, "Počet prvků k výstupu.")
	cmd.Flags().StringVar(&bodyRazeni, "razeni", "", "Razeni")
	cmd.Flags().IntVar(&bodyStart, "start", 0, "Offset pro stránkování (poloha prvního vráceného prvku).")
	cmd.Flags().StringVar(&bodyZdrojCiselniku, "zdroj-ciselniku", "", "Zdroj/oblast číselníku - kód (ciselnikKod: TypZdrojeAres, zdroj:com)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
